-- v004 user_api_credentials — 对应 Python v4。
-- 用户级 API key 加密存储;nonce || ciphertext || tag 全部塞进 encrypted_key。

create table if not exists user_api_credentials (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  api_id text not null,
  encrypted_key bytea not null default ''::bytea,
  base_url_override text not null default '',
  enabled boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, api_id)
);

create index if not exists idx_user_api_creds_user on user_api_credentials(user_id, api_id);
