-- v005 token_usage — 对应 Python v5。
-- LLM 用量与计费记录表。

create table if not exists token_usage (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  save_id bigint references game_saves(id) on delete set null,
  context_run_id bigint references context_runs(id) on delete set null,
  api_id text not null default '',
  model_real_name text not null default '',
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  cached_input_tokens integer not null default 0,
  reasoning_tokens integer not null default 0,
  total_tokens integer not null default 0,
  cost_usd numeric(12,6) not null default 0,
  context_used integer not null default 0,
  context_max integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_token_usage_user_time on token_usage(user_id, created_at desc);
create index if not exists idx_token_usage_save_time on token_usage(save_id, created_at desc);
create index if not exists idx_token_usage_model on token_usage(user_id, api_id, model_real_name);
