-- v007 login_audit — 对应 Python v7。
-- auth.py 之前用 create-if-not-exists 临时建表;这里正式化到 migration。

create table if not exists login_audit (
  id bigint generated by default as identity primary key,
  username text,
  ip text,
  event text not null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_login_audit_user_time on login_audit(username, created_at desc);
create index if not exists idx_login_audit_event on login_audit(event, created_at desc);
