-- v008 user_personas_and_character_cards — 对应 Python v8。
-- 用户级 player 身份卡(杭雁菱穿越者 / 林知意信使 / ...),可跨剧本/存档复用。
-- 以及用户自创的 NPC 卡,可挂任何剧本/存档;scope 区分私有/公开。

create table if not exists user_personas (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  slug text not null,
  name text not null,
  role text not null default '',
  background text not null default '',
  appearance text not null default '',
  personality text not null default '',
  avatar_path text not null default '',
  tags jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  public_id uuid not null default gen_random_uuid(),
  row_version bigint not null default 1,
  unique(user_id, slug)
);

create index if not exists idx_user_personas_user on user_personas(user_id, updated_at desc, id desc);

create table if not exists user_character_cards (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  slug text not null,
  name text not null,
  aliases jsonb not null default '[]'::jsonb,
  identity text not null default '',
  appearance text not null default '',
  personality text not null default '',
  speech_style text not null default '',
  current_status text not null default '',
  secrets text not null default '',
  sample_dialogue jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  token_budget integer not null default 450,
  priority integer not null default 100,
  enabled boolean not null default true,
  scope text not null default 'private',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  public_id uuid not null default gen_random_uuid(),
  row_version bigint not null default 1,
  unique(user_id, slug)
);

create index if not exists idx_user_cards_user on user_character_cards(user_id, enabled, priority desc);
create index if not exists idx_user_cards_name on user_character_cards(user_id, lower(name));
