-- v009 import_jobs — 对应 Python v9。
-- 拆书流水线状态持久化,页面刷新可继续看进度,可取消。

create table if not exists import_jobs (
  id bigint generated by default as identity primary key,
  job_id text unique not null,
  user_id bigint not null references users(id) on delete cascade,
  script_id bigint references scripts(id) on delete set null,
  status text not null default 'pending',
  stage text not null default 'pending',
  stage_progress integer not null default 0,
  stage_total integer not null default 0,
  overall_progress integer not null default 0,
  overall_total integer not null default 5,
  cancel_requested boolean not null default false,
  budget_estimate jsonb not null default '{}'::jsonb,
  usage_actual jsonb not null default '{}'::jsonb,
  stages jsonb not null default '[]'::jsonb,
  error text not null default '',
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_import_jobs_user on import_jobs(user_id, created_at desc);
create index if not exists idx_import_jobs_script on import_jobs(script_id, created_at desc);
