-- v014 script_timeline_anchors — 对应 Python v14。
-- 给"剧本时间线"建一个聚合锚点表。
-- 现状:每本剧本的 chapter_facts 已经有 story_phase + story_time_label,
-- 形成天然的"线性时间线"(初期穿越与火星线 / 柏林暗流篇 / 战争与成长线 / ...),
-- 但没有聚合表,/set 时间 / GM retrieval 都查不到对应章节范围。
-- 这个表把 chapter_facts group by (script_id, story_phase, story_time_label),
-- 拿到 (chapter_min, chapter_max, count, sample),
-- 供 resolve_timeline_anchor(script_id, label) 模糊匹配。

create table if not exists script_timeline_anchors (
  id bigint generated by default as identity primary key,
  script_id bigint not null references scripts(id) on delete cascade,
  story_phase text not null default '',
  story_time_label text not null default '',
  chapter_min integer not null,
  chapter_max integer not null,
  chapter_count integer not null default 0,
  sample_title text not null default '',
  sample_summary text not null default '',
  keywords text[] not null default '{}',
  confidence real not null default 1.0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (script_id, story_phase, story_time_label)
);

create index if not exists ix_sta_script_phase on script_timeline_anchors(script_id, story_phase);
create index if not exists ix_sta_script_label on script_timeline_anchors(script_id, story_time_label);
create index if not exists ix_sta_script_chmin on script_timeline_anchors(script_id, chapter_min);
