-- v015 worldline_convergence_anchors — 对应 Python v15。
-- task 136: 世界线收束机制 (Steins;Gate / 死神来了 风格)
-- 原著的关键事件 (chapter_facts.events + phase_digests.key_events) 是"锚点"。
-- 锚点必须发生,但发生的方式可以变。GM 每一回合知道接下来该发生哪几个锚点,
-- 主动设计场景把剧情往那里引。
--
-- 本表只跟踪锚点的【发生状态】,不复制事件内容。
-- 事件文本按需从 chapter_facts / phase_digests 实时取。
--
-- anchor_key 设计:
--   "chapter:{chapter}:event:{event_idx}"   ← 来自 chapter_facts.events[idx]
--   "phase:{phase_index}:event:{event_idx}" ← 来自 phase_digests.key_events[idx]
-- 这样不会因事件文本变化而失联。

create table if not exists save_anchor_states (
  id bigint generated by default as identity primary key,
  save_id bigint not null references game_saves(id) on delete cascade,
  anchor_key text not null,

  -- 数据来源 (溯源 + 反向查事件内容)
  source_kind text not null default 'chapter',  -- 'chapter' | 'phase'
  source_chapter integer,                         -- chapter_facts.chapter
  source_event_index integer not null default 0,  -- jsonb 数组里的下标
  source_phase_index integer,                     -- phase_digests.phase_index (script 级)
  script_id bigint not null references scripts(id) on delete cascade,

  -- 锚点元数据 (seed 时由 anchor_seed_agent 写入)
  summary text not null,            -- "穆蕾莉娅向 MC 透露异端情报"
  phase_label text not null default '',
  must_preserve jsonb not null default '[]'::jsonb,  -- ["信息传递", "异端话题"]
  may_vary jsonb not null default '[]'::jsonb,       -- ["地点", "时机", "旁观者"]
  importance integer not null default 50,   -- 0-100, 越大越关键
  is_fatal boolean not null default false,  -- true=死神来了模式,玩家任何阻止都失败

  -- 发生状态
  status text not null default 'pending',
    -- pending: 还没发生
    -- occurred: 按原著方式发生 (drift=0)
    -- variant: 以变体方式发生 (drift>0,核心保留)
    -- superseded: 被剧情绕过 (rare,需 reason)
  variant_description text not null default '',
  occurred_at_turn integer,
  drift_score numeric(3,2) not null default 0.0,  -- 0=完全一致 1=完全变体

  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (save_id, anchor_key)
);

create index if not exists idx_anchor_states_save on save_anchor_states(save_id, status);
create index if not exists idx_anchor_states_phase on save_anchor_states(save_id, phase_label, status);
create index if not exists idx_anchor_states_pending_importance on save_anchor_states(save_id, status, importance desc) where status = 'pending';
-- script_id 反向索引,用于 seed 时按 script 拉全量锚点
create index if not exists idx_anchor_states_script on save_anchor_states(script_id, save_id);
