-- v017 sessions_hashed_token — Rust 端原生新增(Python 端未有对应 migration)。
-- 会话表;token_hash 存 SHA-256 hex,不存明文。

create table if not exists sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  token_hash text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  unique(token_hash)
);

create index if not exists idx_sessions_user on sessions(user_id, expires_at desc);
create index if not exists idx_sessions_token_hash on sessions(token_hash);
