-- v017 sessions_hashed_token — Rust 端原生新增(Python 端未有对应 migration)。
-- 会话表;token_hash 存 SHA-256 hex,不存明文。
--
-- 注意:v001 已按 Python init.py 形态创建 sessions(token text primary key, ...),
-- 因此这里必须用 ALTER 把旧表升级为 token_hash 形态,而不能用
-- `create table if not exists`(那样会变 no-op,后续索引引用 token_hash 报错)。
-- fresh DB 时旧表存在但无行,升级幂等;有 Python 历史 sessions 行时会一次性 hash 迁移。

-- 1) 兜底建表(纯 fresh DB 走到这里时本来 v001 已建,但保留以防被外部清表)
create table if not exists sessions (
  token text primary key,
  user_id bigint not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

-- 2) 新增 token_hash 列(允许 NULL,稍后填值后再 NOT NULL)
alter table sessions add column if not exists token_hash text;

-- 3) 把旧 token 哈希成 token_hash(对旧明文 token 一次性迁移)
update sessions
   set token_hash = encode(sha256(convert_to(token, 'UTF8')), 'hex')
 where token_hash is null
   and token is not null;

-- 4) 删除旧的 token 主键 / 列(连同主键约束一起)
alter table sessions drop column if exists token;

-- 5) 新增 id (bigserial) 主键 + last_seen_at
alter table sessions add column if not exists id bigint generated by default as identity;
alter table sessions add column if not exists last_seen_at timestamptz not null default now();

-- 6) token_hash NOT NULL + unique
update sessions set token_hash = encode(sha256(gen_random_bytes(32)), 'hex')
  where token_hash is null;  -- 兜底:孤儿行,生成随机 hash 避免 NOT NULL 失败
alter table sessions alter column token_hash set not null;

-- 旧表的 PRIMARY KEY 在 drop column token 时已经被一并删掉(Postgres 行为);
-- 新主键需通过约束方式补回。
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'sessions_pkey' and conrelid = 'sessions'::regclass
  ) then
    alter table sessions add primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
     where conname = 'sessions_token_hash_uniq' and conrelid = 'sessions'::regclass
  ) then
    alter table sessions add constraint sessions_token_hash_uniq unique(token_hash);
  end if;
end $$;

create index if not exists idx_sessions_user on sessions(user_id, expires_at desc);
create index if not exists idx_sessions_token_hash on sessions(token_hash);
