-- v020 user_card_public_audit — 谁把卡设成 public、什么时候、被多少人读取了。
-- 对应 Wave 2-B user_cards.rs TODO[Sonnet]: admin 审计。

-- 公开卡访问计数:每当 user_cards_for_retrieval 或 list_public_user_cards 命中时递增。
alter table user_character_cards
  add column if not exists public_retrieval_count bigint not null default 0;

-- 公开操作审计日志:scope 变为 public 时写一条。
create table if not exists user_card_public_audit (
  id bigint generated by default as identity primary key,
  card_id bigint not null references user_character_cards(id) on delete cascade,
  card_owner_id bigint not null references users(id) on delete cascade,
  set_by_user_id bigint not null references users(id) on delete cascade,
  scope_before text not null default 'private',
  scope_after text not null default 'public',
  created_at timestamptz not null default now()
);

create index if not exists idx_card_public_audit_card on user_card_public_audit(card_id, created_at desc);
create index if not exists idx_card_public_audit_setby on user_card_public_audit(set_by_user_id, created_at desc);
