-- v021 scripts_and_chapters — Wave 2-A 重做:补完 script_import 流水线所需基表。
--
-- Python 端的 scripts/script_chapters 走 rpg/platform_app/db/init.py 兜底建表,
-- 但 Rust 端只有 014/015/016 等扩展表引用 scripts(...) 外键,从未真正 create。
-- script_import 流水线落库需要这两张表,这里补齐;后续 014/015/016 的引用也终于
-- 能拿到真表(在 fresh DB 上之前会 dangling)。

create table if not exists scripts (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references users(id) on delete cascade,
  title text not null,
  description text not null default '',
  source_path text not null default '',
  chapter_count integer not null default 0,
  word_count integer not null default 0,
  import_report jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_scripts_owner on scripts(owner_id, id desc);

create table if not exists script_chapters (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid(),
  script_id bigint not null references scripts(id) on delete cascade,
  chapter_index integer not null,
  title text not null,
  content text not null,
  word_count integer not null default 0,
  volume_title text not null default '',
  source_marker text not null default '',
  confidence real not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(script_id, chapter_index)
);

create index if not exists idx_script_chapters_script_order
  on script_chapters(script_id, chapter_index);
