-- v022 branches_extended_columns — Wave 2-D 重做:补全 Wave 1A 漏掉的分支表
-- 与扩展列 DDL。
--
-- 背景:Rust 端 rpg-platform/branches 已在使用 branch_commits / branch_refs /
-- branch_nodes / game_saves / runtime_checkouts 这些表,但 Rust DDL 只在 019
-- 建了一张简化版 runtime_checkouts,其余表完全缺。Wave 1A 假设它们由 Python
-- migrations.py 兜底,但 rust-migration 后期要 rust-only 起服务,这里把
-- DDL 补齐到与 Python rpg/platform_app/db/init.py 完全对齐。
--
-- 对照 Python 来源:
--   - 基表 DDL:rpg/platform_app/db/init.py L97..L271
--   - branch_commits.digested_in_phase / digest_at:init.py L150..L156
--   - branch_commits.state_snapshot:init.py L663
--   - branch_refs.is_active:init.py L251(基表定义)
--   - branch_refs.row_version:init.py L656(批量 alter 循环)
--   - runtime_checkouts 5 列:Python migrations.py v1 + init.py L667..L671
--   - game_saves 扩展列:init.py L664..L666

-- ────────────────────────────────────────────────────────────────
-- 基表(Wave 1A 漏建)
-- ────────────────────────────────────────────────────────────────

-- game_saves:save 顶层元数据。
create table if not exists game_saves (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  script_id bigint not null references scripts(id) on delete cascade,
  title text not null,
  state_path text not null,
  active_branch_node_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- branch_nodes:旧版 commit 树节点(Python 走 commits,nodes 现役但偏旁路)。
create table if not exists branch_nodes (
  id bigint generated by default as identity primary key,
  save_id bigint not null references game_saves(id) on delete cascade,
  parent_id bigint references branch_nodes(id) on delete cascade,
  turn_index integer not null,
  role text not null,
  title text not null,
  summary text not null default '',
  content_preview text not null default '',
  state_path text not null default '',
  created_at timestamptz not null default now()
);

-- branch_commits:正式版 commit 树。
create table if not exists branch_commits (
  id bigint generated by default as identity primary key,
  save_id bigint not null references game_saves(id) on delete cascade,
  parent_id bigint references branch_commits(id) on delete cascade,
  object_hash text not null,
  tree_hash text not null default '',
  turn_index integer not null,
  kind text not null,
  title text not null,
  message text not null default '',
  summary text not null default '',
  content_preview text not null default '',
  state_path text not null default '',
  player_input text not null default '',
  gm_output text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(save_id, object_hash)
);

-- branch_refs:分支引用(name → commit_id)。
create table if not exists branch_refs (
  id bigint generated by default as identity primary key,
  save_id bigint not null references game_saves(id) on delete cascade,
  name text not null,
  kind text not null default 'head',
  target_commit_id bigint references branch_commits(id) on delete set null,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(save_id, name)
);

-- ────────────────────────────────────────────────────────────────
-- 扩展列(对齐 Python init.py L658..L671 的 alter 批次)
-- ────────────────────────────────────────────────────────────────

-- branch_nodes:summary 默认列(部分老 schema 没有)。
alter table branch_nodes add column if not exists summary text not null default '';

-- branch_commits:Wave 1A 缺口列
alter table branch_commits add column if not exists state_snapshot jsonb not null default '{}'::jsonb;
alter table branch_commits add column if not exists digested_in_phase integer;
alter table branch_commits add column if not exists digest_at timestamptz;
-- Python L656 的批量循环对 branch_commits 加 row_version + public_id;Rust 端的
-- commits 操作主要靠 object_hash 唯一约束去重,row_version 仍写以匹配前端公共列。
alter table branch_commits add column if not exists row_version bigint not null default 1;
alter table branch_commits add column if not exists public_id uuid not null default gen_random_uuid();
create unique index if not exists idx_branch_commits_public_id on branch_commits(public_id);

-- branch_refs:Python L656 同样加 row_version + public_id。is_active 已在基表里。
alter table branch_refs add column if not exists row_version bigint not null default 1;
alter table branch_refs add column if not exists public_id uuid not null default gen_random_uuid();
create unique index if not exists idx_branch_refs_public_id on branch_refs(public_id);

-- game_saves:active_branch_ref_id / active_commit_id / state_snapshot / active_phase_index
alter table game_saves add column if not exists active_branch_ref_id bigint;
alter table game_saves add column if not exists active_commit_id bigint;
alter table game_saves add column if not exists state_snapshot jsonb not null default '{}'::jsonb;
alter table game_saves add column if not exists active_phase_index integer not null default 0;

-- ────────────────────────────────────────────────────────────────
-- runtime_checkouts:Rust 019 建了简化版,与 Python 不兼容。这里走
-- alter 模式把 Python 期待的全部列补上(Python migrations v1 + init.py)。
-- 注意:Rust 019 的主键是 save_id;Python 版主键是 id+unique(user_id,save_id)。
-- 为保持向后兼容,不动主键,只加 if not exists 列。
-- ────────────────────────────────────────────────────────────────

alter table runtime_checkouts add column if not exists ref_id bigint references branch_refs(id) on delete set null;
alter table runtime_checkouts add column if not exists commit_id bigint references branch_commits(id) on delete set null;
alter table runtime_checkouts add column if not exists runtime_state_path text not null default '';
alter table runtime_checkouts add column if not exists state_snapshot jsonb not null default '{}'::jsonb;
alter table runtime_checkouts add column if not exists snapshot_hash text not null default '';
alter table runtime_checkouts add column if not exists dirty boolean not null default false;
alter table runtime_checkouts add column if not exists turn_at_commit integer not null default 0;
alter table runtime_checkouts add column if not exists turn_runtime integer not null default 0;

-- ────────────────────────────────────────────────────────────────
-- 索引(对齐 Python init.py L680..L689)
-- ────────────────────────────────────────────────────────────────

create index if not exists idx_saves_user on game_saves(user_id, updated_at desc, id desc);
create index if not exists idx_saves_user_script on game_saves(user_id, script_id, id desc);
create index if not exists idx_branch_save on branch_nodes(save_id, id);
create index if not exists idx_branch_parent on branch_nodes(parent_id);
create index if not exists idx_branch_save_turn on branch_nodes(save_id, turn_index, id);
create index if not exists idx_branch_commits_save on branch_commits(save_id, id);
create index if not exists idx_branch_commits_parent on branch_commits(parent_id);
create index if not exists idx_branch_commits_save_turn on branch_commits(save_id, turn_index, id);
create index if not exists idx_branch_refs_save on branch_refs(save_id, id);
create index if not exists idx_branch_refs_target on branch_refs(target_commit_id);
