-- v023 phase_digests — 剧本级阶段摘要表。
--
-- 对应 Python: rpg/scripts/aggregate_phase_digests.py 写入的表。
-- 与 save_phase_digests(存档级,v001 建)不同:
--   - phase_digests   → script 级,由 aggregate_for_script 脚本聚合 chapter_facts 生成
--   - save_phase_digests → save 级,由 phase_digest_agent 对真实游戏存档生成
--
-- 消费方:
--   - rpg-context/src/providers/script_phase_anticipation.rs
--   - rpg-agents/src/worldbook_agent.rs (load_phase_digest_by_label)
--   - rpg-db/src/repos/phase_digests.rs

create table if not exists phase_digests (
  id bigint generated by default as identity primary key,
  script_id bigint not null references scripts(id) on delete cascade,
  phase_index integer not null default 0,         -- 排序用,aggregate 时按 chapter_min 顺序赋
  phase_label text not null,                      -- story_phase 文本,如 "初期穿越与火星线"
  chapter_min integer not null,
  chapter_max integer not null,
  chapter_count integer not null default 0,
  summary text not null default '',
  key_events jsonb not null default '[]'::jsonb,
  key_locations jsonb not null default '[]'::jsonb,
  key_characters jsonb not null default '[]'::jsonb,
  story_time_label_start text not null default '',
  story_time_label_end text not null default '',
  -- 兼容 rpg-db repos 原有字段名
  characters jsonb not null default '[]'::jsonb,   -- alias of key_characters,aggregate 后同步
  world_state jsonb not null default '{}'::jsonb,
  chapter_range_start integer,                     -- alias of chapter_min
  chapter_range_end integer,                       -- alias of chapter_max
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (script_id, phase_label)
);

create index if not exists idx_phase_digests_script_phase on phase_digests(script_id, phase_index);
create index if not exists idx_phase_digests_script_chmin on phase_digests(script_id, chapter_min);
create index if not exists idx_phase_digests_script_label on phase_digests(script_id, phase_label);
