-- 025: script_packs 表 — 剧本元数据包 CRUD
-- 从 rpg-platform/src/script_pack.rs 的 init_script_packs_table 提取

create table if not exists script_packs (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    script_id bigint,
    title text not null default '',
    format_version integer not null default 1,
    chunks_included boolean not null default false,
    byte_size bigint not null default 0,
    checksum text not null default '',
    manifest jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_script_packs_owner
    on script_packs(owner_id, created_at desc);
