from __future__ import annotations

import os
import secrets
import threading
import time
from datetime import datetime, timedelta
from typing import Any

from psycopg.errors import UniqueViolation
from psycopg.types.json import Jsonb

from .db import connect, init_db
from .security import hash_password, normalize_username, verify_password

SESSION_DAYS = 14
MIN_PASSWORD_LENGTH = int(os.environ.get("RPG_MIN_PASSWORD_LENGTH", "8"))

# ── 登录速率限制 ──────────────────────────────────────────────────────────
LOGIN_MAX_FAILS = int(os.environ.get("RPG_LOGIN_MAX_FAILS", "5"))
LOGIN_LOCKOUT_SEC = int(os.environ.get("RPG_LOGIN_LOCKOUT_SEC", "60"))
LOGIN_WINDOW_SEC = int(os.environ.get("RPG_LOGIN_WINDOW_SEC", "300"))  # 5min 内累计失败计数
_FAIL_BUCKETS: dict[str, list[float]] = {}  # key="ip|username" → [失败时间戳...]
_LOCKED_UNTIL: dict[str, float] = {}        # key → 解锁时间
_FAIL_LOCK = threading.Lock()


class RateLimited(Exception):
    """登录被速率限制时抛出"""
    def __init__(self, retry_after_sec: int, key: str):
        self.retry_after_sec = retry_after_sec
        self.key = key
        super().__init__(f"too many failed logins; retry after {retry_after_sec}s")


def _bucket_key(ip: str, username: str) -> str:
    return f"{ip or '-'}|{(username or '').lower()}"


def _check_rate_limit(ip: str, username: str) -> None:
    key = _bucket_key(ip, username)
    now = time.monotonic()
    with _FAIL_LOCK:
        # 已锁定？
        unlock_at = _LOCKED_UNTIL.get(key)
        if unlock_at and now < unlock_at:
            raise RateLimited(int(unlock_at - now), key)
        elif unlock_at:
            _LOCKED_UNTIL.pop(key, None)
        # 清理窗口外的失败记录
        bucket = _FAIL_BUCKETS.get(key, [])
        bucket = [t for t in bucket if now - t < LOGIN_WINDOW_SEC]
        _FAIL_BUCKETS[key] = bucket


def _record_login_fail(ip: str, username: str) -> int:
    """记录一次失败。返回当前窗口内累计失败次数。超阈值会被锁定。"""
    key = _bucket_key(ip, username)
    now = time.monotonic()
    with _FAIL_LOCK:
        bucket = _FAIL_BUCKETS.setdefault(key, [])
        bucket.append(now)
        bucket[:] = [t for t in bucket if now - t < LOGIN_WINDOW_SEC]
        count = len(bucket)
        if count >= LOGIN_MAX_FAILS:
            _LOCKED_UNTIL[key] = now + LOGIN_LOCKOUT_SEC
    _write_audit(username, ip, "login_fail", {"count": count})
    return count


def _record_login_success(ip: str, username: str) -> None:
    key = _bucket_key(ip, username)
    with _FAIL_LOCK:
        _FAIL_BUCKETS.pop(key, None)
        _LOCKED_UNTIL.pop(key, None)
    _write_audit(username, ip, "login_ok", {})


def _write_audit(username: str, ip: str, event: str, meta: dict[str, Any]) -> None:
    try:
        init_db()
        with connect() as db:
            db.execute(
                """
                create table if not exists login_audit (
                  id bigint generated by default as identity primary key,
                  username text,
                  ip text,
                  event text not null,
                  meta jsonb not null default '{}'::jsonb,
                  created_at timestamptz not null default now()
                )
                """
            )
            db.execute(
                "insert into login_audit(username, ip, event, meta) values (%s, %s, %s, %s)",
                (username, ip, event, Jsonb(meta)),
            )
    except Exception:
        pass


def admin_unlock(ip: str, username: str) -> None:
    """admin 手动解锁某个用户/IP（暴露给 /api/admin/login/unlock 用）"""
    key = _bucket_key(ip, username)
    with _FAIL_LOCK:
        _FAIL_BUCKETS.pop(key, None)
        _LOCKED_UNTIL.pop(key, None)
    _write_audit(username, ip, "admin_unlock", {})


def register(username: str, password: str, display_name: str = "") -> dict[str, Any]:
    init_db()
    username = normalize_username(username)
    if not username:
        raise ValueError("用户名不能为空")
    if len(password or "") < MIN_PASSWORD_LENGTH:
        raise ValueError(f"密码至少 {MIN_PASSWORD_LENGTH} 位")
    with connect() as db:
        role = "admin" if db.execute("select count(*) as count from users").fetchone()["count"] == 0 else "user"
        try:
            row = db.execute(
                """
                insert into users(username, password_hash, display_name, role)
                values (%s, %s, %s, %s)
                returning *
                """,
                (username, hash_password(password), (display_name or username).strip(), role),
            ).fetchone()
        except UniqueViolation as exc:
            raise ValueError("用户名已存在") from exc
        return dict(row)


def login(username: str, password: str, *, ip: str = "") -> tuple[dict[str, Any], str]:
    """登录，带速率限制 + 失败审计"""
    init_db()
    normalized = normalize_username(username)
    _check_rate_limit(ip, normalized)  # 锁定中直接抛 RateLimited
    with connect() as db:
        row = db.execute("select * from users where username = %s", (normalized,)).fetchone()
        if not row or not verify_password(password, row["password_hash"]):
            _record_login_fail(ip, normalized)
            raise ValueError("用户名或密码错误")
        token = secrets.token_urlsafe(32)
        expires_at = datetime.now() + timedelta(days=SESSION_DAYS)
        db.execute(
            "insert into sessions(token, user_id, expires_at) values (%s, %s, %s)",
            (token, row["id"], expires_at),
        )
        _record_login_success(ip, normalized)
        return dict(row), token


def logout(token: str | None) -> None:
    if not token:
        return
    init_db()
    with connect() as db:
        db.execute("delete from sessions where token = %s", (token,))


def user_from_token(token: str | None) -> dict[str, Any] | None:
    if not token:
        return None
    init_db()
    with connect() as db:
        row = db.execute(
            """
            select users.* from sessions
            join users on users.id = sessions.user_id
            where sessions.token = %s and sessions.expires_at > now()
            """,
            (token,),
        ).fetchone()
        return dict(row) if row else None


def get_user(user_id: int) -> dict[str, Any]:
    init_db()
    with connect() as db:
        row = db.execute("select * from users where id = %s", (user_id,)).fetchone()
        if not row:
            raise ValueError("用户不存在")
        return dict(row)


def update_profile(user_id: int, display_name: str, bio: str) -> dict[str, Any]:
    init_db()
    with connect() as db:
        row = db.execute(
            "update users set display_name = %s, bio = %s, row_version = row_version + 1, updated_at = now() where id = %s returning *",
            (display_name.strip(), bio.strip(), user_id),
        ).fetchone()
        return dict(row)
