from __future__ import annotations

import hashlib
import os
import secrets
import threading
import time
from datetime import datetime, timedelta, timezone
from typing import Any

from psycopg.errors import UniqueViolation
from psycopg.types.json import Jsonb

from .db import connect, init_db
from .security import hash_password, normalize_username, verify_password

SESSION_DAYS = 14

from core.config import (
    login_lockout_sec as _login_lockout_sec,
)
from core.config import (
    login_max_fails as _login_max_fails,
)
from core.config import (
    login_window_sec as _login_window_sec,
)
from core.config import (
    min_password_length as _min_password_length,
)

MIN_PASSWORD_LENGTH = _min_password_length()

# ── 登录速率限制 ──────────────────────────────────────────────────────────
#
# 警告: 此速率限制使用进程内 dict 实现。
# 多 worker 部署（uvicorn --workers N / gunicorn）下，每个 worker 有独立内存，
# 速率限制 **不在 worker 间共享**，攻击者可以通过轮询 worker 绕过限制。
# 如需多 worker 部署，请将速率限制迁移至 Redis 或数据库后端。
#
LOGIN_MAX_FAILS = _login_max_fails()
LOGIN_LOCKOUT_SEC = _login_lockout_sec()
LOGIN_WINDOW_SEC = _login_window_sec()  # 5min 内累计失败计数
_FAIL_BUCKETS: dict[str, list[float]] = {}  # key="ip|username" → [失败时间戳...]
_LOCKED_UNTIL: dict[str, float] = {}        # key → 解锁时间
_FAIL_LOCK = threading.Lock()

import logging as _logging
_log = _logging.getLogger(__name__)


class RateLimited(Exception):
    """登录被速率限制时抛出"""
    def __init__(self, retry_after_sec: int, key: str):
        self.retry_after_sec = retry_after_sec
        self.key = key
        super().__init__(f"too many failed logins; retry after {retry_after_sec}s")


def _bucket_key(ip: str, username: str) -> str:
    return f"{ip or '-'}|{(username or '').lower()}"


def _check_rate_limit(ip: str, username: str) -> None:
    # 多 worker 部署下此速率限制不安全（每个 worker 独立内存，不共享）
    _log.debug("rate_limit check: ip=%s username=%s (in-process, unsafe under multi-worker)", ip, username)
    key = _bucket_key(ip, username)
    now = time.monotonic()
    with _FAIL_LOCK:
        # 已锁定？
        unlock_at = _LOCKED_UNTIL.get(key)
        if unlock_at and now < unlock_at:
            raise RateLimited(int(unlock_at - now), key)
        elif unlock_at:
            _LOCKED_UNTIL.pop(key, None)
        # 清理窗口外的失败记录
        bucket = _FAIL_BUCKETS.get(key, [])
        bucket = [t for t in bucket if now - t < LOGIN_WINDOW_SEC]
        _FAIL_BUCKETS[key] = bucket


def _record_login_fail(ip: str, username: str) -> int:
    """记录一次失败。返回当前窗口内累计失败次数。超阈值会被锁定。"""
    key = _bucket_key(ip, username)
    now = time.monotonic()
    with _FAIL_LOCK:
        bucket = _FAIL_BUCKETS.setdefault(key, [])
        bucket.append(now)
        bucket[:] = [t for t in bucket if now - t < LOGIN_WINDOW_SEC]
        count = len(bucket)
        if count >= LOGIN_MAX_FAILS:
            _LOCKED_UNTIL[key] = now + LOGIN_LOCKOUT_SEC
    _write_audit(username, ip, "login_fail", {"count": count})
    return count


def _record_login_success(ip: str, username: str) -> None:
    key = _bucket_key(ip, username)
    with _FAIL_LOCK:
        _FAIL_BUCKETS.pop(key, None)
        _LOCKED_UNTIL.pop(key, None)
    _write_audit(username, ip, "login_ok", {})


def _write_audit(username: str, ip: str, event: str, meta: dict[str, Any]) -> None:
    try:
        init_db()
        with connect() as db:
            db.execute(
                """
                create table if not exists login_audit (
                  id bigint generated by default as identity primary key,
                  username text,
                  ip text,
                  event text not null,
                  meta jsonb not null default '{}'::jsonb,
                  created_at timestamptz not null default now()
                )
                """
            )
            db.execute(
                "insert into login_audit(username, ip, event, meta) values (%s, %s, %s, %s)",
                (username, ip, event, Jsonb(meta)),
            )
    except Exception:
        import logging as _logging
        _logging.getLogger(__name__).warning("audit write failed", exc_info=True)


def admin_unlock(ip: str, username: str) -> None:
    """admin 手动解锁某个用户/IP（暴露给 /api/admin/login/unlock 用）"""
    key = _bucket_key(ip, username)
    with _FAIL_LOCK:
        _FAIL_BUCKETS.pop(key, None)
        _LOCKED_UNTIL.pop(key, None)
    _write_audit(username, ip, "admin_unlock", {})


def _bootstrap_admin_allowed(setup_token: str | None) -> bool:
    """首用户(空 users 表)能否被授予 admin。

    - 本地/非鉴权模式:允许(单用户桌面场景,无引导风险)。
    - server/强制鉴权模式:必须配置 RPG_SETUP_TOKEN 且请求携带匹配令牌,
      否则首用户仅为普通 user —— 杜绝公网首注册抢 admin(CWE-269)。
    """
    from core.config import effective_auth_required
    from core.config import setup_token as _cfg_setup_token
    if not effective_auth_required():
        return True
    configured = (_cfg_setup_token() or "").strip()
    provided = (setup_token or "").strip()
    if not configured or not provided:
        return False
    return secrets.compare_digest(provided, configured)


def register(
    username: str,
    password: str,
    display_name: str = "",
    *,
    setup_token: str | None = None,
) -> dict[str, Any]:
    init_db()
    username = normalize_username(username)
    if not username:
        raise ValueError("用户名不能为空")
    if len(password or "") > 1024:
        raise ValueError("密码超长")
    if len(password or "") < MIN_PASSWORD_LENGTH:
        raise ValueError(f"密码至少 {MIN_PASSWORD_LENGTH} 位")
    allow_admin = _bootstrap_admin_allowed(setup_token)
    pw_hash = hash_password(password)
    disp = (display_name or username).strip()
    with connect() as db:
        try:
            if allow_admin:
                # 防 TOCTOU：用条件 INSERT，只有当 users 表中还没有 admin 时才插入 admin 角色
                row = db.execute(
                    """
                    insert into users(username, password_hash, display_name, role)
                    values (
                        %s, %s, %s,
                        CASE WHEN NOT EXISTS (SELECT 1 FROM users WHERE role = 'admin')
                             THEN 'admin'
                             ELSE 'user'
                        END
                    )
                    returning *
                    """,
                    (username, pw_hash, disp),
                ).fetchone()
            else:
                row = db.execute(
                    """
                    insert into users(username, password_hash, display_name, role)
                    values (%s, %s, %s, 'user')
                    returning *
                    """,
                    (username, pw_hash, disp),
                ).fetchone()
        except UniqueViolation as exc:
            raise ValueError("注册失败，请检查输入后重试") from exc
        return dict(row)


def _hash_token(token: str) -> str:
    """session token → sha256 hex(DB 只存哈希,不存明文)。"""
    return hashlib.sha256((token or "").encode("utf-8")).hexdigest()


def login(username: str, password: str, *, ip: str = "") -> tuple[dict[str, Any], str]:
    """登录，带速率限制 + 失败审计"""
    if len(password or "") > 1024:
        raise ValueError("密码超长")
    init_db()
    normalized = normalize_username(username)
    _check_rate_limit(ip, normalized)  # 锁定中直接抛 RateLimited
    with connect() as db:
        row = db.execute("select * from users where username = %s", (normalized,)).fetchone()
        if not row or not verify_password(password, row["password_hash"]):
            _record_login_fail(ip, normalized)
            raise ValueError("用户名或密码错误")
        token = secrets.token_urlsafe(32)
        # 使用 timezone-aware UTC 时间, 避免 server 本地时区漂移 session 过期
        expires_at = datetime.now(timezone.utc) + timedelta(days=SESSION_DAYS)
        # 安全:DB 只存 token 的 sha256 哈希,不存可直接使用的明文(拖库不得有效会话)
        # 注: token 列保留为 '' 兼容老 schema, 后续 migration 删除该列
        db.execute(
            "insert into sessions(token, token_hash, user_id, expires_at) values (%s, %s, %s, %s)",
            ("", _hash_token(token), row["id"], expires_at),
        )
        _record_login_success(ip, normalized)
        return dict(row), token


def logout(token: str | None) -> None:
    if not token:
        return
    init_db()
    with connect() as db:
        # 仅按 token_hash 删除。旧的明文 token 兼容分支已废弃 — 拖库后不允许重放。
        # 历史明文行需运维一次性清空（update sessions set token='' where token<>''）。
        db.execute("delete from sessions where token_hash = %s", (_hash_token(token),))


def user_from_token(token: str | None) -> dict[str, Any] | None:
    if not token:
        return None
    init_db()
    with connect() as db:
        # 仅按 token_hash 查找。旧明文行已不接受 — 拖库后历史 token 立即失效。
        row = db.execute(
            """
            select users.* from sessions
            join users on users.id = sessions.user_id
            where sessions.token_hash = %s
              and sessions.expires_at > now()
            """,
            (_hash_token(token),),
        ).fetchone()
        return dict(row) if row else None


def get_user(user_id: int) -> dict[str, Any]:
    init_db()
    with connect() as db:
        row = db.execute("select * from users where id = %s", (user_id,)).fetchone()
        if not row:
            raise ValueError("用户不存在")
        return dict(row)


def update_profile(user_id: int, display_name: str, bio: str) -> dict[str, Any]:
    init_db()
    with connect() as db:
        row = db.execute(
            "update users set display_name = %s, bio = %s, row_version = row_version + 1, updated_at = now() where id = %s returning *",
            (display_name.strip(), bio.strip(), user_id),
        ).fetchone()
        return dict(row)
