"""Frontend-driven supplementary routes.

These endpoints back the Claude Design front-end (Login.html, Platform.html,
Game Console.html). They live in a separate router so the existing api.py
can be edited independently without merge collisions.

Mount in ui.py with:

    from platform_app.frontend_routes import router as frontend_router
    app.include_router(frontend_router)
"""
from __future__ import annotations

import csv
import io
import json
import os
import time
from datetime import datetime
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, StreamingResponse

from . import auth as _auth
from .api import (
    SESSION_COOKIE,
    _delete_session_cookie,
    json_response,
    require_user,
)
from .db import connect, expose, init_db
from .security import hash_password, verify_password

router = APIRouter()


# ------------------------------------------------------------
#  Helpers
# ------------------------------------------------------------
def _bad(msg: str, status: int = 400):
    return json_response({"ok": False, "error": msg}, status_code=status)


def _client_ip(request: Request) -> str:
    return (request.client.host if request.client else "") or ""


# ------------------------------------------------------------
#  AUTH supplements
# ------------------------------------------------------------
@router.post("/api/auth/password")
async def api_change_password(request: Request):
    """Change current user's password (`current` -> `next`)."""
    user = require_user(request)
    body = await request.json()
    cur_pw = body.get("current") or ""
    next_pw = body.get("next") or ""
    if len(next_pw) < _auth.MIN_PASSWORD_LENGTH:
        return _bad(f"新密码至少 {_auth.MIN_PASSWORD_LENGTH} 位")
    init_db()
    with connect() as db:
        row = db.execute("select password_hash from users where id = %s", (user["id"],)).fetchone()
        if not row or not verify_password(cur_pw, row["password_hash"]):
            return _bad("当前密码错误")
        db.execute(
            "update users set password_hash = %s, row_version = row_version + 1, updated_at = now() where id = %s",
            (hash_password(next_pw), user["id"]),
        )
        # Optional: revoke all OTHER sessions (keep current cookie).
        token = request.cookies.get(SESSION_COOKIE)
        if token:
            db.execute("delete from sessions where user_id = %s and token <> %s", (user["id"], token))
    return json_response({"ok": True, "message": "密码已修改"})


@router.get("/api/auth/login-history")
async def api_login_history(request: Request):
    """Return last N login_audit rows for the current user. ?format=csv supported."""
    user = require_user(request)
    init_db()
    fmt = (request.query_params.get("format") or "").lower()
    limit = max(1, min(int(request.query_params.get("limit") or 50), 500))
    with connect() as db:
        db.execute(
            """
            create table if not exists login_audit (
              id bigint generated by default as identity primary key,
              username text, ip text, event text not null,
              meta jsonb not null default '{}'::jsonb,
              created_at timestamptz not null default now()
            )
            """
        )
        rows = db.execute(
            """
            select id, username, ip, event, meta, created_at
            from login_audit
            where username = %s
            order by created_at desc
            limit %s
            """,
            (user.get("username"), limit),
        ).fetchall()
    items = [
        {
            "id": r["id"],
            "at": r["created_at"].isoformat() if r["created_at"] else None,
            "ip": r["ip"],
            "user_agent": (r["meta"] or {}).get("ua") if isinstance(r["meta"], dict) else None,
            "result": "ok" if r["event"] == "login_ok" else "blocked",
            "event": r["event"],
        }
        for r in rows
    ]
    if fmt == "csv":
        buf = io.StringIO()
        w = csv.writer(buf)
        w.writerow(["at", "ip", "event", "result"])
        for i in items:
            w.writerow([i.get("at"), i.get("ip"), i.get("event"), i.get("result")])
        return StreamingResponse(
            io.BytesIO(buf.getvalue().encode("utf-8")),
            media_type="text/csv; charset=utf-8",
            headers={"Content-Disposition": 'attachment; filename="login-history.csv"'},
        )
    return json_response({"ok": True, "entries": items})


@router.get("/api/auth/sessions")
async def api_list_sessions(request: Request):
    user = require_user(request)
    init_db()
    cur_token = request.cookies.get(SESSION_COOKIE)
    with connect() as db:
        rows = db.execute(
            """
            select token, user_id, created_at, expires_at
            from sessions
            where user_id = %s and expires_at > now()
            order by created_at desc
            """,
            (user["id"],),
        ).fetchall()
    out = []
    for r in rows:
        token = r["token"]
        out.append({
            "id": token[-12:],  # truncated, never expose the full token
            "session_id": token[-12:],
            "created_at": r["created_at"].isoformat() if r["created_at"] else None,
            "expires_at": r["expires_at"].isoformat() if r["expires_at"] else None,
            "last_seen_at": r["created_at"].isoformat() if r["created_at"] else None,
            "current": token == cur_token,
        })
    return json_response({"ok": True, "sessions": out})


@router.post("/api/auth/sessions/revoke")
async def api_revoke_session(request: Request):
    user = require_user(request)
    body = await request.json()
    sid = body.get("session_id") or body.get("id") or ""
    if not sid:
        return _bad("缺少 session_id")
    init_db()
    cur_token = request.cookies.get(SESSION_COOKIE) or ""
    with connect() as db:
        # match by suffix (we exposed only last 12 chars)
        deleted = db.execute(
            "delete from sessions where user_id = %s and token like %s and token <> %s returning token",
            (user["id"], f"%{sid}", cur_token),
        ).fetchone()
    return json_response({"ok": True, "deleted": bool(deleted)})


@router.post("/api/auth/sessions/revoke-all")
async def api_revoke_all_sessions(request: Request):
    user = require_user(request)
    init_db()
    cur_token = request.cookies.get(SESSION_COOKIE) or ""
    with connect() as db:
        n = db.execute(
            "delete from sessions where user_id = %s and token <> %s",
            (user["id"], cur_token),
        ).statusmessage
    return json_response({"ok": True, "result": n})


@router.post("/api/auth/sms-code")
async def api_sms_code(request: Request):
    """Stub: we don't actually have an SMS gateway. Pretend success."""
    require_user(request)
    body = await request.json()
    phone = (body.get("phone") or "").strip()
    if not phone:
        return _bad("请提供手机号")
    # In a real deployment plug in an SMS provider here.
    return json_response({"ok": True, "message": "验证码已发送（演示）", "expires_in_sec": 60})


@router.post("/api/auth/sms-verify")
async def api_sms_verify(request: Request):
    """Stub: accept any 4-6 digit code for demo purposes."""
    require_user(request)
    body = await request.json()
    code = (body.get("code") or "").strip()
    if not code.isdigit() or not (4 <= len(code) <= 6):
        return _bad("验证码无效")
    return json_response({"ok": True, "verified": True})


# ------------------------------------------------------------
#  PROFILE supplements
# ------------------------------------------------------------
_UPLOAD_ROOT = Path(__file__).resolve().parent.parent / "platform_data" / "avatars"


@router.post("/api/profile/avatar")
async def api_upload_avatar(request: Request):
    user = require_user(request)
    form = await request.form()
    f = form.get("file")
    if not f or not getattr(f, "filename", ""):
        return _bad("请选择文件")
    ext = os.path.splitext(f.filename or "")[-1].lower()
    if ext not in {".png", ".jpg", ".jpeg", ".webp"}:
        return _bad("仅支持 PNG / JPG / WEBP")
    _UPLOAD_ROOT.mkdir(parents=True, exist_ok=True)
    safe_name = f"u{user['id']}_{int(time.time())}{ext}"
    dest = _UPLOAD_ROOT / safe_name
    data = await f.read()
    if len(data) > 2 * 1024 * 1024:
        return _bad("文件超过 2 MB")
    dest.write_bytes(data)
    avatar_url = f"/api/profile/avatar/file/{safe_name}"
    init_db()
    with connect() as db:
        db.execute(
            "update users set avatar_url = %s, updated_at = now() where id = %s",
            (avatar_url, user["id"]),
        )
    return json_response({"ok": True, "avatar_url": avatar_url})


@router.post("/api/profile/avatar/reset")
async def api_reset_avatar(request: Request):
    user = require_user(request)
    init_db()
    with connect() as db:
        db.execute("update users set avatar_url = null, updated_at = now() where id = %s", (user["id"],))
    return json_response({"ok": True})


@router.get("/api/profile/avatar/file/{name}")
async def api_avatar_file(name: str):
    # Basic safety: only allow our generated naming pattern.
    if "/" in name or "\\" in name or name.startswith("."):
        raise HTTPException(404)
    path = _UPLOAD_ROOT / name
    if not path.exists():
        raise HTTPException(404)
    return FileResponse(str(path))


def _ensure_profile_extras_table() -> None:
    init_db()
    with connect() as db:
        db.execute(
            """
            create table if not exists profile_extras (
              user_id bigint primary key references users(id) on delete cascade,
              real_name text default '',
              gender text default 'unspecified',
              birthday text default '',
              location text default '',
              website text default '',
              pronouns text default '',
              language text default 'zh-CN',
              timezone text default 'Asia/Shanghai',
              email text default '',
              phone text default '',
              visibility jsonb not null default '{}'::jsonb,
              preferences jsonb not null default '{}'::jsonb,
              updated_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            "alter table users add column if not exists avatar_url text"
        )


@router.post("/api/profile/visibility")
async def api_profile_visibility(request: Request):
    user = require_user(request)
    body = await request.json() or {}
    _ensure_profile_extras_table()
    from psycopg.types.json import Jsonb
    with connect() as db:
        db.execute(
            """
            insert into profile_extras(user_id, visibility)
            values (%s, %s)
            on conflict (user_id) do update set visibility = excluded.visibility, updated_at = now()
            """,
            (user["id"], Jsonb(body)),
        )
    return json_response({"ok": True, "visibility": body})


# Persist any additional “me/preference” keys here too.
@router.post("/api/me/preference")
async def api_save_preference(request: Request):
    user = require_user(request)
    body = await request.json() or {}
    _ensure_profile_extras_table()
    from psycopg.types.json import Jsonb
    # Merge over existing preferences
    with connect() as db:
        row = db.execute(
            "select preferences from profile_extras where user_id = %s",
            (user["id"],),
        ).fetchone()
        prefs = (row and row["preferences"]) or {}
        prefs.update(body)
        db.execute(
            """
            insert into profile_extras(user_id, preferences)
            values (%s, %s)
            on conflict (user_id) do update set preferences = excluded.preferences, updated_at = now()
            """,
            (user["id"], Jsonb(prefs)),
        )
    return json_response({"ok": True, "preferences": prefs})


@router.get("/api/me/profile")
async def api_me_profile(request: Request):
    user = require_user(request)
    _ensure_profile_extras_table()
    with connect() as db:
        row = db.execute(
            "select * from profile_extras where user_id = %s",
            (user["id"],),
        ).fetchone()
    extras = expose(row) if row else {}
    extras.pop("user_id", None)
    return json_response({
        "ok": True,
        "profile": {
            "id": user["id"],
            "username": user["username"],
            "display_name": user.get("display_name") or "",
            "bio": user.get("bio") or "",
            "role": user.get("role"),
            "avatar_url": user.get("avatar_url"),
            **extras,
        },
    })


# ------------------------------------------------------------
#  ACCOUNT lifecycle
# ------------------------------------------------------------
@router.post("/api/account/export")
async def api_account_export(request: Request):
    user = require_user(request)
    body = await request.json() or {}
    # Record the request; do not actually ship a tarball (out of scope here).
    init_db()
    with connect() as db:
        db.execute(
            """
            create table if not exists account_exports (
              id bigint generated by default as identity primary key,
              user_id bigint not null references users(id) on delete cascade,
              scope text default 'all', format text default 'zip',
              email text, status text default 'pending',
              created_at timestamptz not null default now()
            )
            """
        )
        db.execute(
            "insert into account_exports(user_id, scope, format, email) values (%s, %s, %s, %s)",
            (user["id"], body.get("scope", "all"), body.get("format", "zip"), body.get("email", "")),
        )
    return json_response({"ok": True, "message": "导出申请已记录，完成后会邮件通知"})


@router.post("/api/account/deactivate")
async def api_account_deactivate(request: Request):
    user = require_user(request)
    init_db()
    with connect() as db:
        db.execute(
            "update users set deactivated_at = now(), updated_at = now() where id = %s",
            (user["id"],),
        )
        db.execute("delete from sessions where user_id = %s", (user["id"],))
    return json_response({"ok": True})


@router.post("/api/account/delete")
async def api_account_delete(request: Request):
    user = require_user(request)
    init_db()
    with connect() as db:
        # Cascade clean-up handled by schema; remove the user row.
        db.execute("delete from sessions where user_id = %s", (user["id"],))
        db.execute("delete from users where id = %s", (user["id"],))
    resp = json_response({"ok": True})
    # 跟 _set_session_cookie 一致的 samesite/secure,否则跨域场景下浏览器不认 delete
    _delete_session_cookie(resp, request)
    return resp


# ------------------------------------------------------------
#  SAVES supplements
# ------------------------------------------------------------
@router.post("/api/saves/{save_id}/delete")
async def api_save_delete(save_id: int, request: Request):
    user = require_user(request)
    init_db()
    with connect() as db:
        owned = db.execute(
            "select 1 from game_saves where id = %s and user_id = %s",
            (save_id, user["id"]),
        ).fetchone()
        if not owned:
            return _bad("无权操作该存档", 403)
        db.execute("delete from game_saves where id = %s and user_id = %s", (save_id, user["id"]))
    return json_response({"ok": True})


@router.post("/api/saves/{save_id}/rename")
async def api_save_rename(save_id: int, request: Request):
    user = require_user(request)
    body = await request.json()
    title = (body.get("title") or "").strip()
    if not title:
        return _bad("标题不能为空")
    init_db()
    with connect() as db:
        owned = db.execute(
            "select 1 from game_saves where id = %s and user_id = %s",
            (save_id, user["id"]),
        ).fetchone()
        if not owned:
            return _bad("无权操作该存档", 403)
        db.execute(
            "update game_saves set title = %s, updated_at = now() where id = %s",
            (title, save_id),
        )
    return json_response({"ok": True, "title": title})


@router.post("/api/saves/{save_id}/activate")
async def api_save_activate(save_id: int, request: Request):
    """task 30：之前只 select 1 验证归属就返 ok=True，既不写 user_runtime，
    也不清 ui._state_by_user 缓存 → 用户点完「继续」跳到 Game Console，
    GET /api/state 拿到的是上一个 active save 的 player/world。

    现在：调用 branches.activate_save → runtime.activate_state_snapshot
    把 user_runtime 切到目标 save 的 active commit；并清掉 ui 进程内 state 缓存，
    下一次 _ensure_loaded 会从 user_runtime 重新加载新 save 的 state。"""
    user = require_user(request)
    from . import branches as _branches
    try:
        result = _branches.activate_save(user["id"], save_id)
    except ValueError as exc:
        return _bad(str(exc), 403)
    # 清 ui 模块内的 per-user state 缓存（跨模块耦合：ui 在主进程内长期持有 cache，
    # activate 必须告诉它丢掉旧 save 的 state，否则 GET /api/state 仍读旧档）。
    try:
        import app as _ui
        _ui._invalidate_user_cache(user)
    except Exception:
        pass
    return json_response(result)


@router.get("/api/saves/{save_id}/export")
async def api_save_export(save_id: int, request: Request):
    user = require_user(request)
    init_db()
    with connect() as db:
        row = db.execute(
            "select id, title, state_snapshot, created_at, updated_at from game_saves where id = %s and user_id = %s",
            (save_id, user["id"]),
        ).fetchone()
    if not row:
        raise HTTPException(404)
    payload = {
        "id": row["id"],
        "title": row["title"],
        "exported_at": datetime.now().isoformat(),
        "state": row["state_snapshot"],
    }
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    safe_title = (row["title"] or f"save-{save_id}").replace("/", "_")
    return StreamingResponse(
        io.BytesIO(body.encode("utf-8")),
        media_type="application/json; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{safe_title}.json"'},
    )


# ------------------------------------------------------------
#  CHARACTER CARDS supplements
# ------------------------------------------------------------
@router.post("/api/me/character-cards/import-json")
async def api_card_import_json(request: Request):
    user = require_user(request)
    body = await request.json() or {}
    raw = body.get("json") or ""
    try:
        data = json.loads(raw) if isinstance(raw, str) else raw
    except Exception:
        return _bad("JSON 解析失败")
    # Accept a variety of shapes (SillyTavern v1/v2 etc.)
    name = data.get("name") or data.get("char_name") or ""
    if not name:
        return _bad("缺少 name 字段")
    from . import user_cards as _uc
    card = _uc.upsert_user_card(user["id"], {
        "name": name,
        "description": data.get("description") or data.get("personality") or "",
        "first_message": data.get("first_mes") or data.get("first_message") or "",
        "tags": data.get("tags") or [],
        "source": "import-json",
    })
    return json_response({"ok": True, "card": card})


# ------------------------------------------------------------
#  MODELS supplements (visibility & validate)
# ------------------------------------------------------------
@router.post("/api/models/visibility")
async def api_models_visibility(request: Request):
    """Toggle visibility flags for individual models.

    Writes through upsert_model so DB + JSON catalog stay in sync.
    Previously wrote only to model_entries.enabled, which diverged from the
    catalog JSON on restart when DB was unavailable.
    """
    require_user(request)
    body = await request.json() or {}
    api_id = body.get("api_id") or body.get("api")
    model_real_name = body.get("model") or body.get("real_name")
    visible = body.get("visible")
    if not api_id or model_real_name is None or visible is None:
        return _bad("缺少参数")
    from model_registry import find_api, load_model_catalog, upsert_model
    catalog = load_model_catalog()
    api = find_api(catalog, api_id)
    if not api:
        return _bad(f"未知 API: {api_id}")
    # locate model by real_name or id
    model_entry = next(
        (m for m in api.get("models", []) if m.get("real_name") == model_real_name or m.get("id") == model_real_name),
        None,
    )
    if not model_entry:
        return _bad(f"模型不存在: {model_real_name}")
    # upsert_model merges into catalog and calls save_model_catalog (writes DB + JSON)
    upsert_model(api_id, {**model_entry, "enabled": bool(visible)})
    return json_response({"ok": True})


@router.post("/api/models/validate")
async def api_models_validate(request: Request):
    """Lightweight credentials probe — defers to model_probe.list_remote_models."""
    user = require_user(request)
    body = await request.json() or {}
    api_id = body.get("api_id") or body.get("api_slug") or body.get("api") or ""
    try:
        from model_probe import list_remote_models, probe_availability
        if body.get("model"):
            out = probe_availability(
                api_id=api_id,
                model_real_name=body.get("model"),
                user_id=user["id"],
                timeout_sec=int(body.get("timeout", 8)),
            )
        else:
            out = list_remote_models(api_id=api_id, force_refresh=True, user_id=user["id"])
        return json_response({"ok": True, **(out if isinstance(out, dict) else {"result": out})})
    except Exception as e:
        return json_response({"ok": False, "error": str(e)}, status_code=400)


# ------------------------------------------------------------
#  SEARCH
# ------------------------------------------------------------
@router.get("/api/search")
async def api_search(request: Request):
    """Cross-resource search. Returns grouped results (scripts, saves, cards, chapters)."""
    user = require_user(request)
    q = (request.query_params.get("q") or "").strip()
    if not q:
        return json_response({"ok": True, "groups": []})
    pattern = f"%{q}%"
    init_db()
    groups = []
    with connect() as db:
        scripts = db.execute(
            "select id, title, description from scripts where owner_id = %s and title ilike %s limit 8",
            (user["id"], pattern),
        ).fetchall()
        if scripts:
            groups.append({"kind": "scripts", "items": [
                {"id": r["id"], "label": r["title"], "sub": r["description"], "href": "Platform.html#scripts"} for r in scripts
            ]})
        saves = db.execute(
            "select id, title from game_saves where user_id = %s and title ilike %s limit 8",
            (user["id"], pattern),
        ).fetchall()
        if saves:
            groups.append({"kind": "saves", "items": [
                {"id": r["id"], "label": r["title"], "href": "Platform.html#saves"} for r in saves
            ]})
        try:
            cards = db.execute(
                "select id, name from character_cards where owner_user_id = %s and name ilike %s limit 8",
                (user["id"], pattern),
            ).fetchall()
            if cards:
                groups.append({"kind": "cards", "items": [
                    {"id": r["id"], "label": r["name"], "href": "Platform.html#cards"} for r in cards
                ]})
        except Exception:
            pass
    return json_response({"ok": True, "groups": groups, "query": q})


# ------------------------------------------------------------
#  Plugins / Skills lists (frontend convenience)
# ------------------------------------------------------------
@router.get("/api/plugins")
async def api_plugins(request: Request):
    """Reuse /api/tools but slice the 'plugins' channel for the CapPage."""
    from tools_dsl.tool_registry import tool_payload
    payload = tool_payload()
    return json_response({"ok": True, "plugins": payload.get("plugins", [])})


@router.get("/api/skills")
async def api_skills_list(request: Request):
    require_user(request)
    from tools_dsl.tool_registry import tool_payload
    payload = tool_payload()
    return json_response({"ok": True, "skills": payload.get("skills", [])})


# ------------------------------------------------------------
#  Admin: SMTP test (button in DeploySection)
# ------------------------------------------------------------
@router.post("/api/admin/smtp/test")
async def api_admin_smtp_test(request: Request):
    """task 51：FE DeploySection 有「发送测试邮件」按钮但后端从未实现。
    返回明确的"未配置"错误，让 UI 显示真实失败而不是 404 黑洞。

    真正实现需要：读 user_preferences (SMTP host/port/user/pass/from) →
    smtplib.SMTP(host, port).login(user, pass).sendmail(from, to, msg)。
    现在 SMTP 配置还存在 user_preferences 待规范化阶段，先给清晰的占位错误。
    """
    user = require_user(request)
    if user.get("role") != "admin":
        return json_response({"ok": False, "error": "需要管理员权限"}, status_code=403)
    return json_response({
        "ok": False,
        "error": "SMTP 尚未在 user_preferences 中规范化存储 · 请先在「部署 → 邮件 SMTP」配置并保存",
        "configured": False,
    }, status_code=503)
