//! script_pack —— 剧本元数据包 CRUD。
//!
//! 对应 Python `rpg/platform_app/knowledge/script_pack.py`。
//!
//! Pack 是一份剧本的 zip 形式打包(manifest + script + chapters/facts/cards/...),
//! 跨用户共享的"分享格式"。本模块只做元数据层 CRUD —— 记录哪个用户在何时
//! 导出/导入了哪个剧本生成的包,以及包元信息(标题、format_version、size、
//! checksum 等)。具体的 zip 解压/打包流程后续由 routes/library 接管。
//!
//! 表:`script_packs(id, owner_id, script_id, title, format_version,
//!   chunks_included, byte_size, checksum, manifest, created_at)`。
//! DDL 已迁移到 `rpg-db/migrations/025_script_packs.sql`,
//! `init_script_packs_table` 保留但 CRUD 不再调用(依赖迁移)。

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::{PgPool, Row};

use crate::error::{PlatformError, PlatformResult};

pub const FORMAT_VERSION: i32 = 1;
pub const MAX_ZIP_BYTES: i64 = 50 * 1024 * 1024;

/// `script_packs` 表一行。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScriptPackRow {
    pub id: i64,
    pub owner_id: i64,
    pub script_id: Option<i64>,
    pub title: String,
    pub format_version: i32,
    pub chunks_included: bool,
    pub byte_size: i64,
    pub checksum: String,
    pub manifest: Value,
    pub created_at: DateTime<Utc>,
}

/// 入参,创建一条 pack 元数据(zip 已经落到某个对象存储,此处只记元信息)。
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ScriptPackPayload {
    pub script_id: Option<i64>,
    pub title: String,
    #[serde(default = "default_format")]
    pub format_version: i32,
    #[serde(default)]
    pub chunks_included: bool,
    #[serde(default)]
    pub byte_size: i64,
    #[serde(default)]
    pub checksum: String,
    #[serde(default)]
    pub manifest: Value,
}

fn default_format() -> i32 {
    FORMAT_VERSION
}

fn row_to_pack(row: &sqlx::postgres::PgRow) -> sqlx::Result<ScriptPackRow> {
    Ok(ScriptPackRow {
        id: row.try_get("id")?,
        owner_id: row.try_get("owner_id")?,
        script_id: row.try_get::<Option<i64>, _>("script_id").unwrap_or(None),
        title: row.try_get::<String, _>("title").unwrap_or_default(),
        format_version: row.try_get::<i32, _>("format_version").unwrap_or(FORMAT_VERSION),
        chunks_included: row.try_get::<bool, _>("chunks_included").unwrap_or(false),
        byte_size: row.try_get::<i64, _>("byte_size").unwrap_or(0),
        checksum: row.try_get::<String, _>("checksum").unwrap_or_default(),
        manifest: row
            .try_get::<Value, _>("manifest")
            .unwrap_or(Value::Object(Default::default())),
        created_at: row
            .try_get::<DateTime<Utc>, _>("created_at")
            .unwrap_or_else(|_| Utc::now()),
    })
}

const TABLE_DDL: &str = "create table if not exists script_packs (\
      id bigint generated by default as identity primary key,\
      owner_id bigint not null,\
      script_id bigint,\
      title text not null default '',\
      format_version integer not null default 1,\
      chunks_included boolean not null default false,\
      byte_size bigint not null default 0,\
      checksum text not null default '',\
      manifest jsonb not null default '{}'::jsonb,\
      created_at timestamptz not null default now()\
    )";

const TABLE_INDEX_DDL: &str =
    "create index if not exists idx_script_packs_owner on script_packs(owner_id, created_at desc)";

/// 兜底建表,确保 script_packs / 索引存在。
/// 已迁移到 025_script_packs.sql;保留此函数供非迁移场景(如测试)使用。
pub async fn init_script_packs_table(pool: &PgPool) -> PlatformResult<()> {
    sqlx::query(TABLE_DDL).execute(pool).await?;
    sqlx::query(TABLE_INDEX_DDL).execute(pool).await?;
    Ok(())
}

/// 创建一条 pack 元记录。
pub async fn create_pack(
    pool: &PgPool,
    owner_id: i64,
    payload: ScriptPackPayload,
) -> PlatformResult<ScriptPackRow> {
    if payload.byte_size > MAX_ZIP_BYTES {
        return Err(PlatformError::validation(format!(
            "pack 超过 {} MB 上限",
            MAX_ZIP_BYTES / 1024 / 1024
        )));
    }
    if payload.format_version != FORMAT_VERSION {
        return Err(PlatformError::validation(format!(
            "unsupported format_version: {} (expected {FORMAT_VERSION})",
            payload.format_version
        )));
    }
    let manifest = if payload.manifest.is_null() {
        Value::Object(Default::default())
    } else {
        payload.manifest
    };
    let row = sqlx::query(
        "insert into script_packs(owner_id, script_id, title, format_version, \
           chunks_included, byte_size, checksum, manifest) \
         values ($1, $2, $3, $4, $5, $6, $7, $8) returning *",
    )
    .bind(owner_id)
    .bind(payload.script_id)
    .bind(payload.title.trim())
    .bind(payload.format_version)
    .bind(payload.chunks_included)
    .bind(payload.byte_size)
    .bind(payload.checksum.trim())
    .bind(&manifest)
    .fetch_one(pool)
    .await?;
    Ok(row_to_pack(&row)?)
}

/// 按用户列出 pack。
pub async fn list_packs(
    pool: &PgPool,
    owner_id: i64,
    limit: i64,
) -> PlatformResult<Vec<ScriptPackRow>> {
    let limit = limit.clamp(1, 500);
    let rows = sqlx::query(
        "select * from script_packs where owner_id = $1 order by id desc limit $2",
    )
    .bind(owner_id)
    .bind(limit)
    .fetch_all(pool)
    .await?;
    rows.iter()
        .map(row_to_pack)
        .collect::<Result<Vec<_>, _>>()
        .map_err(Into::into)
}

/// 取单个 pack。
pub async fn get_pack(
    pool: &PgPool,
    owner_id: i64,
    pack_id: i64,
) -> PlatformResult<Option<ScriptPackRow>> {
    let row = sqlx::query("select * from script_packs where id = $1 and owner_id = $2")
        .bind(pack_id)
        .bind(owner_id)
        .fetch_optional(pool)
        .await?;
    Ok(row.map(|r| row_to_pack(&r)).transpose()?)
}

/// 列出某剧本的所有 pack 元(允许其他用户读 — 配合 scope=public 共享场景)。
pub async fn list_packs_by_script(
    pool: &PgPool,
    script_id: i64,
    limit: i64,
) -> PlatformResult<Vec<ScriptPackRow>> {
    let limit = limit.clamp(1, 500);
    let rows = sqlx::query(
        "select * from script_packs where script_id = $1 order by id desc limit $2",
    )
    .bind(script_id)
    .bind(limit)
    .fetch_all(pool)
    .await?;
    rows.iter()
        .map(row_to_pack)
        .collect::<Result<Vec<_>, _>>()
        .map_err(Into::into)
}

/// 删除 pack 元(只允许 owner)。
pub async fn delete_pack(
    pool: &PgPool,
    owner_id: i64,
    pack_id: i64,
) -> PlatformResult<bool> {
    let res = sqlx::query("delete from script_packs where id = $1 and owner_id = $2")
        .bind(pack_id)
        .bind(owner_id)
        .execute(pool)
        .await?;
    Ok(res.rows_affected() > 0)
}

/// 解析 manifest.json bytes 并校验 format_version。返回反序列化后的 Value。
pub fn parse_manifest(text: &str) -> PlatformResult<Value> {
    let v: Value = serde_json::from_str(text)?;
    let fv = v
        .get("format_version")
        .and_then(|x| x.as_i64())
        .ok_or_else(|| PlatformError::validation("manifest 缺少 format_version"))?;
    if fv as i32 != FORMAT_VERSION {
        return Err(PlatformError::validation(format!(
            "unsupported format_version: {fv} (expected {FORMAT_VERSION})"
        )));
    }
    Ok(v)
}

/// 计算 byte_size + sha256 校验和(辅助 routes 层在上传 zip 时使用)。
pub fn compute_checksum(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(bytes);
    let out = h.finalize();
    let mut s = String::with_capacity(out.len() * 2);
    for b in out {
        s.push_str(&format!("{:02x}", b));
    }
    s
}
