//! session —— Session 管理 (login_audit + active_sessions)。
//!
//! 对应 Python `rpg/platform_app/auth.py` 中 `sessions` 表 + `login_audit` 表
//! 操作的查询/审计部分(注册/登录主流程在 `auth/sessions.rs` 完成)。
//!
//! 提供:
//! - `record_login_audit` 写一条登录事件(login_ok/login_fail/admin_unlock)
//! - `list_login_audit` 翻审计日志(管理员视角)
//! - `list_active_sessions` 列出某用户当前未过期 token(去 password_hash)
//! - `revoke_session` / `revoke_all_user_sessions` 主动失活
//! - `cleanup_expired_sessions` 定期清理已过期 token
//!
//! 表 DDL `login_audit` 已在 rpg-db migrations 里;本模块兜底 CREATE IF NOT EXISTS。

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::{PgPool, Row};

use crate::error::PlatformResult;

const AUDIT_DDL: &str = "create table if not exists login_audit (\
      id bigint generated by default as identity primary key,\
      username text,\
      ip text,\
      event text not null,\
      meta jsonb not null default '{}'::jsonb,\
      created_at timestamptz not null default now()\
    )";

const AUDIT_INDEX_DDL: &str =
    "create index if not exists idx_login_audit_user_time on login_audit(username, created_at desc)";
const AUDIT_EVENT_INDEX_DDL: &str =
    "create index if not exists idx_login_audit_event on login_audit(event, created_at desc)";

/// 兜底建 login_audit 表。
pub async fn init_login_audit_table(pool: &PgPool) -> PlatformResult<()> {
    sqlx::query(AUDIT_DDL).execute(pool).await?;
    sqlx::query(AUDIT_INDEX_DDL).execute(pool).await?;
    sqlx::query(AUDIT_EVENT_INDEX_DDL).execute(pool).await?;
    Ok(())
}

/// `login_audit` 一行。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoginAuditRow {
    pub id: i64,
    pub username: Option<String>,
    pub ip: Option<String>,
    pub event: String,
    pub meta: Value,
    pub created_at: DateTime<Utc>,
}

fn row_to_audit(row: &sqlx::postgres::PgRow) -> sqlx::Result<LoginAuditRow> {
    Ok(LoginAuditRow {
        id: row.try_get("id")?,
        username: row.try_get::<Option<String>, _>("username").unwrap_or(None),
        ip: row.try_get::<Option<String>, _>("ip").unwrap_or(None),
        event: row.try_get::<String, _>("event").unwrap_or_default(),
        meta: row
            .try_get::<Value, _>("meta")
            .unwrap_or(Value::Object(Default::default())),
        created_at: row
            .try_get::<DateTime<Utc>, _>("created_at")
            .unwrap_or_else(|_| Utc::now()),
    })
}

/// 写一条审计。失败吞掉(不阻塞登录主流程,语义与 Python 一致)。
pub async fn record_login_audit(
    pool: &PgPool,
    username: &str,
    ip: &str,
    event: &str,
    meta: Value,
) {
    if init_login_audit_table(pool).await.is_err() {
        return;
    }
    let _ = sqlx::query(
        "insert into login_audit(username, ip, event, meta) values ($1, $2, $3, $4)",
    )
    .bind(if username.is_empty() {
        None
    } else {
        Some(username)
    })
    .bind(if ip.is_empty() { None } else { Some(ip) })
    .bind(event)
    .bind(&meta)
    .execute(pool)
    .await;
}

/// 翻审计日志(可按 username + event 过滤)。
pub async fn list_login_audit(
    pool: &PgPool,
    username: Option<&str>,
    event: Option<&str>,
    limit: i64,
) -> PlatformResult<Vec<LoginAuditRow>> {
    init_login_audit_table(pool).await?;
    let limit = limit.clamp(1, 500);
    let mut sql = String::from("select * from login_audit where 1=1");
    if username.is_some() {
        sql.push_str(" and username = $2");
    }
    if event.is_some() {
        if username.is_some() {
            sql.push_str(" and event = $3");
        } else {
            sql.push_str(" and event = $2");
        }
    }
    sql.push_str(" order by id desc limit $1");
    let mut q = sqlx::query(&sql).bind(limit);
    if let Some(u) = username {
        q = q.bind(u);
    }
    if let Some(e) = event {
        q = q.bind(e);
    }
    let rows = q.fetch_all(pool).await?;
    rows.iter()
        .map(row_to_audit)
        .collect::<Result<Vec<_>, _>>()
        .map_err(Into::into)
}

// ─── active_sessions(基于 sessions 表的查询视图)─────────────────────

/// 一条未过期 session。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActiveSession {
    pub token_prefix: String,
    pub user_id: i64,
    pub expires_at: DateTime<Utc>,
    #[serde(default)]
    pub created_at: Option<DateTime<Utc>>,
}

fn mask_token(token: &str) -> String {
    let mut iter = token.chars();
    let head: String = iter.by_ref().take(6).collect();
    format!("{head}...")
}

/// 列出用户当前所有未过期 session(token 仅暴露前 6 位前缀)。
pub async fn list_active_sessions(
    pool: &PgPool,
    user_id: i64,
) -> PlatformResult<Vec<ActiveSession>> {
    let rows = sqlx::query(
        "select token, user_id, expires_at, \
                (select created_at from sessions s2 where s2.token = sessions.token) as created_at \
           from sessions \
          where user_id = $1 and expires_at > now() \
          order by expires_at desc",
    )
    .bind(user_id)
    .fetch_all(pool)
    .await?;
    let mut out = Vec::with_capacity(rows.len());
    for r in rows {
        let token: String = r.try_get("token")?;
        out.push(ActiveSession {
            token_prefix: mask_token(&token),
            user_id: r.try_get::<i64, _>("user_id").unwrap_or(user_id),
            expires_at: r
                .try_get::<DateTime<Utc>, _>("expires_at")
                .unwrap_or_else(|_| Utc::now()),
            created_at: r.try_get::<Option<DateTime<Utc>>, _>("created_at").ok().flatten(),
        });
    }
    Ok(out)
}

/// 主动失活一条 session(按 token,需 owner)。
pub async fn revoke_session(pool: &PgPool, user_id: i64, token: &str) -> PlatformResult<bool> {
    if token.is_empty() {
        return Ok(false);
    }
    let res = sqlx::query("delete from sessions where token = $1 and user_id = $2")
        .bind(token)
        .bind(user_id)
        .execute(pool)
        .await?;
    Ok(res.rows_affected() > 0)
}

/// 失活某用户全部 token(改密 / 强制下线场景)。返回删除条数。
pub async fn revoke_all_user_sessions(pool: &PgPool, user_id: i64) -> PlatformResult<u64> {
    let res = sqlx::query("delete from sessions where user_id = $1")
        .bind(user_id)
        .execute(pool)
        .await?;
    Ok(res.rows_affected())
}

/// 清理已过期 session。返回删除条数。
pub async fn cleanup_expired_sessions(pool: &PgPool) -> PlatformResult<u64> {
    let res = sqlx::query("delete from sessions where expires_at <= now()")
        .execute(pool)
        .await?;
    Ok(res.rows_affected())
}
