//! migrations.rs — 对应 rpg/platform_app/db/migrations.py
//!
//! 设计：
//!   - `MigrationStep` 描述一个版本化迁移条目（id + name + sql 字符串切片）。
//!   - `MIGRATIONS` 是所有已知迁移的静态数组；001-003 已翻译，004-016 为 TODO。
//!   - `run_migrations(pool)` 负责：
//!       1. 用 pg_advisory_lock 串行化 DDL
//!       2. 确保 schema_migrations 表存在
//!       3. 跳过已应用的版本，顺序执行未应用的版本
//!
//! Python 原版用 `pg_advisory_lock`（阻塞），这里用 `pg_try_advisory_lock` 轮询
//! （避免 sqlx 长时间持有事务连接），超时后返回 `DbError::LockTimeout`。

use sqlx::postgres::PgPool;
use std::time::{Duration, Instant};

use crate::pool::DbError;

// Postgres advisory lock ID，与 Python 端保持一致：
//   'rpg_platform_migrate' → 0x52504D49475254AB
const MIGRATION_ADVISORY_LOCK_ID: i64 = 0x52504D49475254ABu64 as i64;

/// 单个版本化迁移条目。
///
/// 对应 Python: `(version: int, name: str, statements: list[str])`
/// 这里把所有 SQL 语句合并为一个 `sql` 字段（用分号分隔），由 `run_migrations` 拆分执行。
pub struct MigrationStep {
    pub id: i64,
    pub name: &'static str,
    /// 本步骤的所有 SQL 语句，多条以 `\x00` 分隔（见 `split_sql`）。
    pub sql: &'static str,
}

// ──────────────────────────────────────────────────────────────
//  已翻译的迁移（001-003）
// ──────────────────────────────────────────────────────────────

/// 迁移 001 — 初始 schema（从 SQL 文件内联加载）。
static SQL_001: &str = include_str!("../migrations/001_init.sql");

/// 迁移 002 — 补全 context_runs 状态列（对应 Python v2 ensure_context_runs_status）。
static SQL_002: &str = concat!(
    "alter table context_runs add column if not exists status text not null default 'done'",
    "\x00",
    "alter table context_runs add column if not exists error text not null default ''",
    "\x00",
    "alter table context_runs add column if not exists duration_ms integer not null default 0",
    "\x00",
    "alter table context_runs add column if not exists started_at timestamptz not null default now()",
);

/// 迁移 003 — model_apis 增加 base_url 列（对应 Python v3 ensure_model_apis_base_url）。
static SQL_003: &str =
    "alter table model_apis add column if not exists base_url text not null default ''";

/// 迁移 004 — user_api_credentials 用户级 API key 加密存储表。
static SQL_004: &str = concat!(
    "create table if not exists user_api_credentials (\
      id bigint generated by default as identity primary key,\
      user_id bigint not null references users(id) on delete cascade,\
      api_id text not null,\
      encrypted_key bytea not null default ''::bytea,\
      base_url_override text not null default '',\
      enabled boolean not null default true,\
      metadata jsonb not null default '{}'::jsonb,\
      created_at timestamptz not null default now(),\
      updated_at timestamptz not null default now(),\
      unique(user_id, api_id)\
    )",
    "\x00",
    "create index if not exists idx_user_api_creds_user on user_api_credentials(user_id, api_id)",
);

/// 迁移 005 — token_usage 用量计费表。
static SQL_005: &str = concat!(
    "create table if not exists token_usage (\
      id bigint generated by default as identity primary key,\
      user_id bigint not null references users(id) on delete cascade,\
      save_id bigint references game_saves(id) on delete set null,\
      context_run_id bigint references context_runs(id) on delete set null,\
      api_id text not null default '',\
      model_real_name text not null default '',\
      input_tokens integer not null default 0,\
      output_tokens integer not null default 0,\
      cached_input_tokens integer not null default 0,\
      reasoning_tokens integer not null default 0,\
      total_tokens integer not null default 0,\
      cost_usd numeric(12,6) not null default 0,\
      context_used integer not null default 0,\
      context_max integer not null default 0,\
      metadata jsonb not null default '{}'::jsonb,\
      created_at timestamptz not null default now()\
    )",
    "\x00",
    "create index if not exists idx_token_usage_user_time on token_usage(user_id, created_at desc)",
    "\x00",
    "create index if not exists idx_token_usage_save_time on token_usage(save_id, created_at desc)",
    "\x00",
    "create index if not exists idx_token_usage_model on token_usage(user_id, api_id, model_real_name)",
);

/// 迁移 006 — user_preferences jsonb 偏好表。
static SQL_006: &str =
    "create table if not exists user_preferences (\
      user_id bigint primary key references users(id) on delete cascade,\
      preferences jsonb not null default '{}'::jsonb,\
      updated_at timestamptz not null default now()\
    )";

/// 迁移 007 — login_audit 登录审计表。
static SQL_007: &str = concat!(
    "create table if not exists login_audit (\
      id bigint generated by default as identity primary key,\
      username text,\
      ip text,\
      event text not null,\
      meta jsonb not null default '{}'::jsonb,\
      created_at timestamptz not null default now()\
    )",
    "\x00",
    "create index if not exists idx_login_audit_user_time on login_audit(username, created_at desc)",
    "\x00",
    "create index if not exists idx_login_audit_event on login_audit(event, created_at desc)",
);

/// 迁移 008 — user_personas + user_character_cards。
static SQL_008: &str = concat!(
    "create table if not exists user_personas (\
      id bigint generated by default as identity primary key,\
      user_id bigint not null references users(id) on delete cascade,\
      slug text not null,\
      name text not null,\
      role text not null default '',\
      background text not null default '',\
      appearance text not null default '',\
      personality text not null default '',\
      avatar_path text not null default '',\
      tags jsonb not null default '[]'::jsonb,\
      metadata jsonb not null default '{}'::jsonb,\
      is_default boolean not null default false,\
      created_at timestamptz not null default now(),\
      updated_at timestamptz not null default now(),\
      public_id uuid not null default gen_random_uuid(),\
      row_version bigint not null default 1,\
      unique(user_id, slug)\
    )",
    "\x00",
    "create index if not exists idx_user_personas_user on user_personas(user_id, updated_at desc, id desc)",
    "\x00",
    "create table if not exists user_character_cards (\
      id bigint generated by default as identity primary key,\
      user_id bigint not null references users(id) on delete cascade,\
      slug text not null,\
      name text not null,\
      aliases jsonb not null default '[]'::jsonb,\
      identity text not null default '',\
      appearance text not null default '',\
      personality text not null default '',\
      speech_style text not null default '',\
      current_status text not null default '',\
      secrets text not null default '',\
      sample_dialogue jsonb not null default '[]'::jsonb,\
      tags jsonb not null default '[]'::jsonb,\
      metadata jsonb not null default '{}'::jsonb,\
      token_budget integer not null default 450,\
      priority integer not null default 100,\
      enabled boolean not null default true,\
      scope text not null default 'private',\
      created_at timestamptz not null default now(),\
      updated_at timestamptz not null default now(),\
      public_id uuid not null default gen_random_uuid(),\
      row_version bigint not null default 1,\
      unique(user_id, slug)\
    )",
    "\x00",
    "create index if not exists idx_user_cards_user on user_character_cards(user_id, enabled, priority desc)",
    "\x00",
    "create index if not exists idx_user_cards_name on user_character_cards(user_id, lower(name))",
);

/// 迁移 009 — import_jobs 拆书流水线状态持久化。
static SQL_009: &str = concat!(
    "create table if not exists import_jobs (\
      id bigint generated by default as identity primary key,\
      job_id text unique not null,\
      user_id bigint not null references users(id) on delete cascade,\
      script_id bigint references scripts(id) on delete set null,\
      status text not null default 'pending',\
      stage text not null default 'pending',\
      stage_progress integer not null default 0,\
      stage_total integer not null default 0,\
      overall_progress integer not null default 0,\
      overall_total integer not null default 5,\
      cancel_requested boolean not null default false,\
      budget_estimate jsonb not null default '{}'::jsonb,\
      usage_actual jsonb not null default '{}'::jsonb,\
      stages jsonb not null default '[]'::jsonb,\
      error text not null default '',\
      started_at timestamptz,\
      finished_at timestamptz,\
      created_at timestamptz not null default now(),\
      updated_at timestamptz not null default now()\
    )",
    "\x00",
    "create index if not exists idx_import_jobs_user on import_jobs(user_id, created_at desc)",
    "\x00",
    "create index if not exists idx_import_jobs_script on import_jobs(script_id, created_at desc)",
);

/// 迁移 010 — pgvector 条件建 vector 列 + HNSW 索引（DO $$ 块）。
static SQL_010: &str =
    "do $$\n\
    begin\n\
      if exists (select 1 from pg_extension where extname = 'vector') then\n\
        execute 'alter table document_chunks add column if not exists embedding_vec vector(768)';\n\
        execute 'alter table memories add column if not exists embedding_vec vector(768)';\n\
        execute 'create index if not exists idx_doc_chunks_embedding_hnsw on document_chunks using hnsw (embedding_vec vector_cosine_ops)';\n\
        execute 'create index if not exists idx_memories_embedding_hnsw on memories using hnsw (embedding_vec vector_cosine_ops)';\n\
      end if;\n\
    end $$";

/// 迁移 011 — user_runtime DB 化。
static SQL_011: &str = concat!(
    "create table if not exists user_runtime (\
      user_id bigint primary key references users(id) on delete cascade,\
      save_id bigint references game_saves(id) on delete set null,\
      active_commit_id bigint,\
      active_branch_node_id bigint,\
      active_ref_id bigint,\
      source_state_path text not null default '',\
      runtime_state_path text not null default '',\
      game_url text not null default '/',\
      metadata jsonb not null default '{}'::jsonb,\
      updated_at timestamptz not null default now()\
    )",
    "\x00",
    "create index if not exists idx_user_runtime_save on user_runtime(save_id)",
);

/// 迁移 012 — import_jobs 增加 kind 列。
static SQL_012: &str = concat!(
    "alter table import_jobs add column if not exists kind text not null default 'full_pipeline'",
    "\x00",
    "create index if not exists idx_import_jobs_kind_user on import_jobs(kind, user_id, status, created_at desc)",
);

/// 迁移 013 — import_jobs 单活跃唯一索引 + heartbeat 列。
static SQL_013: &str = concat!(
    "create unique index if not exists uq_import_jobs_active_per_script \
    on import_jobs(user_id, script_id, kind) \
    where status in ('pending', 'running')",
    "\x00",
    "alter table import_jobs add column if not exists heartbeat_at timestamptz",
    "\x00",
    "create index if not exists idx_import_jobs_heartbeat on import_jobs(status, heartbeat_at) where status = 'running'",
);

/// 迁移 014 — script_timeline_anchors 剧本时间线锚点表。
static SQL_014: &str = concat!(
    "create table if not exists script_timeline_anchors (\
      id bigint generated by default as identity primary key,\
      script_id bigint not null references scripts(id) on delete cascade,\
      story_phase text not null default '',\
      story_time_label text not null default '',\
      chapter_min integer not null,\
      chapter_max integer not null,\
      chapter_count integer not null default 0,\
      sample_title text not null default '',\
      sample_summary text not null default '',\
      keywords text[] not null default '{}',\
      confidence real not null default 1.0,\
      created_at timestamptz not null default now(),\
      updated_at timestamptz not null default now(),\
      unique (script_id, story_phase, story_time_label)\
    )",
    "\x00",
    "create index if not exists ix_sta_script_phase on script_timeline_anchors(script_id, story_phase)",
    "\x00",
    "create index if not exists ix_sta_script_label on script_timeline_anchors(script_id, story_time_label)",
    "\x00",
    "create index if not exists ix_sta_script_chmin on script_timeline_anchors(script_id, chapter_min)",
);

/// 迁移 015 — save_anchor_states 世界线收束锚点状态表。
static SQL_015: &str = concat!(
    "create table if not exists save_anchor_states (\
      id bigint generated by default as identity primary key,\
      save_id bigint not null references game_saves(id) on delete cascade,\
      anchor_key text not null,\
      source_kind text not null default 'chapter',\
      source_chapter integer,\
      source_event_index integer not null default 0,\
      source_phase_index integer,\
      script_id bigint not null references scripts(id) on delete cascade,\
      summary text not null,\
      phase_label text not null default '',\
      must_preserve jsonb not null default '[]'::jsonb,\
      may_vary jsonb not null default '[]'::jsonb,\
      importance integer not null default 50,\
      is_fatal boolean not null default false,\
      status text not null default 'pending',\
      variant_description text not null default '',\
      occurred_at_turn integer,\
      drift_score numeric(3,2) not null default 0.0,\
      metadata jsonb not null default '{}'::jsonb,\
      created_at timestamptz not null default now(),\
      updated_at timestamptz not null default now(),\
      unique (save_id, anchor_key)\
    )",
    "\x00",
    "create index if not exists idx_anchor_states_save on save_anchor_states(save_id, status)",
    "\x00",
    "create index if not exists idx_anchor_states_phase on save_anchor_states(save_id, phase_label, status)",
    "\x00",
    "create index if not exists idx_anchor_states_pending_importance on save_anchor_states(save_id, status, importance desc) where status = 'pending'",
    "\x00",
    "create index if not exists idx_anchor_states_script on save_anchor_states(script_id, save_id)",
);

/// 迁移 016 — script_overrides 剧本 overrides 元数据表。
static SQL_016: &str = concat!(
    "create table if not exists script_overrides (\
      script_id bigint primary key references scripts(id) on delete cascade,\
      data jsonb not null default '{}'::jsonb,\
      updated_at timestamptz not null default now()\
    )",
    "\x00",
    "create index if not exists idx_script_overrides_updated on script_overrides(updated_at)",
);

/// 所有迁移的静态列表。
///
/// 顺序必须严格按 id 升序；`run_migrations` 依赖此约束跳过已应用版本。
pub static MIGRATIONS: &[MigrationStep] = &[
    MigrationStep { id: 1,  name: "initial_schema",                          sql: SQL_001 },
    MigrationStep { id: 2,  name: "ensure_context_runs_status",              sql: SQL_002 },
    MigrationStep { id: 3,  name: "ensure_model_apis_base_url",              sql: SQL_003 },
    MigrationStep { id: 4,  name: "user_api_credentials",                    sql: SQL_004 },
    MigrationStep { id: 5,  name: "token_usage",                             sql: SQL_005 },
    MigrationStep { id: 6,  name: "user_preferences",                        sql: SQL_006 },
    MigrationStep { id: 7,  name: "login_audit",                             sql: SQL_007 },
    MigrationStep { id: 8,  name: "user_personas_and_character_cards",       sql: SQL_008 },
    MigrationStep { id: 9,  name: "import_jobs",                             sql: SQL_009 },
    MigrationStep { id: 10, name: "pgvector_columns_and_hnsw",               sql: SQL_010 },
    MigrationStep { id: 11, name: "user_runtime_db_backed",                  sql: SQL_011 },
    MigrationStep { id: 12, name: "import_jobs_kind_for_durable_sync",       sql: SQL_012 },
    MigrationStep { id: 13, name: "import_jobs_single_active_per_script",    sql: SQL_013 },
    MigrationStep { id: 14, name: "script_timeline_anchors",                 sql: SQL_014 },
    MigrationStep { id: 15, name: "worldline_convergence_anchors",           sql: SQL_015 },
    MigrationStep { id: 16, name: "script_overrides",                        sql: SQL_016 },
];

// ──────────────────────────────────────────────────────────────
//  辅助：拆分 SQL 语句
// ──────────────────────────────────────────────────────────────

/// 将 `\x00` 分隔的多条 SQL 拆回独立语句。
/// 对于从文件加载的 001，直接返回原始字符串整体（整个文件作为一条执行）。
fn split_sql(sql: &str) -> Vec<&str> {
    if sql.contains('\x00') {
        sql.split('\x00').filter(|s| !s.trim().is_empty()).collect()
    } else {
        // 文件型 SQL：原样整体执行（包含多语句事务时由 PG 驱动处理）
        vec![sql]
    }
}

// ──────────────────────────────────────────────────────────────
//  Advisory lock（try 轮询版）
// ──────────────────────────────────────────────────────────────

/// 尝试获取 Postgres advisory lock，最多等待 `timeout_ms` 毫秒。
///
/// 对应 Python `_migration_advisory_lock()` 的 `pg_advisory_lock`（阻塞版），
/// 这里改用 `pg_try_advisory_lock` 轮询，避免 sqlx 连接长期挂起。
async fn acquire_advisory_lock(pool: &PgPool, timeout_ms: u64) -> Result<(), DbError> {
    let deadline = Instant::now() + Duration::from_millis(timeout_ms);
    loop {
        let locked: bool = sqlx::query_scalar(
            "SELECT pg_try_advisory_lock($1)",
        )
        .bind(MIGRATION_ADVISORY_LOCK_ID)
        .fetch_one(pool)
        .await?;

        if locked {
            return Ok(());
        }
        if Instant::now() >= deadline {
            return Err(DbError::LockTimeout { timeout_ms });
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
}

/// 释放 advisory lock（即使失败也只记日志，不 panic）。
async fn release_advisory_lock(pool: &PgPool) {
    let result: Result<bool, _> = sqlx::query_scalar(
        "SELECT pg_advisory_unlock($1)",
    )
    .bind(MIGRATION_ADVISORY_LOCK_ID)
    .fetch_one(pool)
    .await;

    if let Err(e) = result {
        tracing::warn!("pg_advisory_unlock failed (ignored): {e}");
    }
}

// ──────────────────────────────────────────────────────────────
//  公开入口
// ──────────────────────────────────────────────────────────────

/// 运行所有未应用的迁移。
///
/// 对应 Python `_apply_versioned_migrations()` + `_migration_advisory_lock()`。
///
/// 步骤：
/// 1. 获取 advisory lock（超时 5000 ms）
/// 2. 确保 `schema_migrations` 表存在
/// 3. 查已应用版本集合
/// 4. 按序执行未应用的迁移，并写入 `schema_migrations`
/// 5. 释放 advisory lock
pub async fn run_migrations(pool: &PgPool) -> Result<(), DbError> {
    const LOCK_TIMEOUT_MS: u64 = 5_000;

    acquire_advisory_lock(pool, LOCK_TIMEOUT_MS).await?;

    let result = do_run_migrations(pool).await;

    release_advisory_lock(pool).await;

    result
}

async fn do_run_migrations(pool: &PgPool) -> Result<(), DbError> {
    // 确保 schema_migrations 表存在（对应 Python 同名 DDL）
    sqlx::query(
        "CREATE TABLE IF NOT EXISTS schema_migrations (
           version  integer PRIMARY KEY,
           name     text    NOT NULL,
           applied_at timestamptz NOT NULL DEFAULT now()
         )",
    )
    .execute(pool)
    .await?;

    // 查询已应用版本
    let applied: Vec<i64> = sqlx::query_scalar("SELECT version FROM schema_migrations")
        .fetch_all(pool)
        .await?;
    let applied_set: std::collections::HashSet<i64> = applied.into_iter().collect();

    for step in MIGRATIONS {
        if applied_set.contains(&step.id) {
            tracing::debug!("migration v{} '{}' already applied, skipping", step.id, step.name);
            continue;
        }

        tracing::info!("applying migration v{} '{}'", step.id, step.name);

        for stmt in split_sql(step.sql) {
            sqlx::query(stmt)
                .execute(pool)
                .await
                .map_err(|e| DbError::Migration(
                    format!("v{} '{}': {e}", step.id, step.name)
                ))?;
        }

        sqlx::query(
            "INSERT INTO schema_migrations(version, name) VALUES ($1, $2)
             ON CONFLICT DO NOTHING",
        )
        .bind(step.id)
        .bind(step.name)
        .execute(pool)
        .await?;

        tracing::info!("migration v{} '{}' done", step.id, step.name);
    }

    Ok(())
}
