from __future__ import annotations

import os
from contextlib import contextmanager
from typing import Any

import psycopg

from platform_app.db.connection import database_url


def _get_connect():
    """运行时动态取 connect，支持测试 monkey-patch platform_app.db.connect。"""
    import platform_app.db as _db_pkg  # 函数内 import，避免循环依赖
    return _db_pkg.connect


def _get_migrations():
    """运行时动态取 MIGRATIONS，支持测试 monkey-patch platform_app.db.MIGRATIONS。"""
    import platform_app.db as _db_pkg  # 函数内 import，避免循环依赖
    return _db_pkg.MIGRATIONS


# Postgres advisory lock 唯一 ID（任意 int64 即可，固定即可）
# 'rpg_platform_migrate' 的 hash → 一个稳定的常量
MIGRATION_ADVISORY_LOCK_ID = 0x52504D49475254AB  # "RPMIGRT" + ab
from core.config import migration_lock_timeout_ms as _migration_lock_timeout_ms

MIGRATION_LOCK_TIMEOUT_MS = _migration_lock_timeout_ms()


# ══════════════════════════════════════════════════════════════════════
#  版本化 migration 框架
# ══════════════════════════════════════════════════════════════════════
# 每个 migration 是 (version: int, name: str, statements: list[str])。
# version 必须单调递增；statements 按顺序执行。每次 init_db 完成后调用，
# 已应用的 version 不会重复执行。
#
# 新增 schema 变更请添加新条目，不要修改已发布的旧条目。
MIGRATIONS: list[tuple[int, str, list[str]]] = [
    (1, "ensure_runtime_dirty_columns", [
        # 与 init_db 里已有的兼容；这里只是声明被 versioned 接管
        "alter table runtime_checkouts add column if not exists snapshot_hash text not null default ''",
        "alter table runtime_checkouts add column if not exists dirty boolean not null default false",
        "alter table runtime_checkouts add column if not exists turn_at_commit integer not null default 0",
        "alter table runtime_checkouts add column if not exists turn_runtime integer not null default 0",
    ]),
    (2, "ensure_context_runs_status", [
        "alter table context_runs add column if not exists status text not null default 'done'",
        "alter table context_runs add column if not exists error text not null default ''",
        "alter table context_runs add column if not exists duration_ms integer not null default 0",
        "alter table context_runs add column if not exists started_at timestamptz not null default now()",
    ]),
    (3, "ensure_model_apis_base_url", [
        # OpenAI 兼容 provider 需要可配置 base_url
        "alter table model_apis add column if not exists base_url text not null default ''",
    ]),
    (4, "user_api_credentials", [
        # 用户级 API key 加密存储；nonce || ciphertext || tag 全部塞进 encrypted_key
        """
        create table if not exists user_api_credentials (
          id bigint generated by default as identity primary key,
          user_id bigint not null references users(id) on delete cascade,
          api_id text not null,
          encrypted_key bytea not null default ''::bytea,
          base_url_override text not null default '',
          enabled boolean not null default true,
          metadata jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now(),
          unique(user_id, api_id)
        )
        """,
        "create index if not exists idx_user_api_creds_user on user_api_credentials(user_id, api_id)",
    ]),
    (5, "token_usage", [
        """
        create table if not exists token_usage (
          id bigint generated by default as identity primary key,
          user_id bigint not null references users(id) on delete cascade,
          save_id bigint references game_saves(id) on delete set null,
          context_run_id bigint references context_runs(id) on delete set null,
          api_id text not null default '',
          model_real_name text not null default '',
          input_tokens integer not null default 0,
          output_tokens integer not null default 0,
          cached_input_tokens integer not null default 0,
          reasoning_tokens integer not null default 0,
          total_tokens integer not null default 0,
          cost_usd numeric(12,6) not null default 0,
          context_used integer not null default 0,
          context_max integer not null default 0,
          metadata jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now()
        )
        """,
        "create index if not exists idx_token_usage_user_time on token_usage(user_id, created_at desc)",
        "create index if not exists idx_token_usage_save_time on token_usage(save_id, created_at desc)",
        "create index if not exists idx_token_usage_model on token_usage(user_id, api_id, model_real_name)",
    ]),
    (6, "user_preferences", [
        """
        create table if not exists user_preferences (
          user_id bigint primary key references users(id) on delete cascade,
          preferences jsonb not null default '{}'::jsonb,
          updated_at timestamptz not null default now()
        )
        """,
    ]),
    (7, "login_audit", [
        # auth.py 之前用 create-if-not-exists 临时建表；这里正式化到 migration
        """
        create table if not exists login_audit (
          id bigint generated by default as identity primary key,
          username text,
          ip text,
          event text not null,
          meta jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now()
        )
        """,
        "create index if not exists idx_login_audit_user_time on login_audit(username, created_at desc)",
        "create index if not exists idx_login_audit_event on login_audit(event, created_at desc)",
    ]),
    (8, "user_personas_and_character_cards", [
        # 用户级 player 身份卡（杭雁菱穿越者 / 林知意信使 / ...），可跨剧本/存档复用
        """
        create table if not exists user_personas (
          id bigint generated by default as identity primary key,
          user_id bigint not null references users(id) on delete cascade,
          slug text not null,
          name text not null,
          role text not null default '',
          background text not null default '',
          appearance text not null default '',
          personality text not null default '',
          avatar_path text not null default '',
          tags jsonb not null default '[]'::jsonb,
          metadata jsonb not null default '{}'::jsonb,
          is_default boolean not null default false,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now(),
          public_id uuid not null default gen_random_uuid(),
          row_version bigint not null default 1,
          unique(user_id, slug)
        )
        """,
        "create index if not exists idx_user_personas_user on user_personas(user_id, updated_at desc, id desc)",
        # 用户自创的 NPC 卡，可挂任何剧本/存档；scope 区分私有/公开
        """
        create table if not exists user_character_cards (
          id bigint generated by default as identity primary key,
          user_id bigint not null references users(id) on delete cascade,
          slug text not null,
          name text not null,
          aliases jsonb not null default '[]'::jsonb,
          identity text not null default '',
          appearance text not null default '',
          personality text not null default '',
          speech_style text not null default '',
          current_status text not null default '',
          secrets text not null default '',
          sample_dialogue jsonb not null default '[]'::jsonb,
          tags jsonb not null default '[]'::jsonb,
          metadata jsonb not null default '{}'::jsonb,
          token_budget integer not null default 450,
          priority integer not null default 100,
          enabled boolean not null default true,
          scope text not null default 'private',
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now(),
          public_id uuid not null default gen_random_uuid(),
          row_version bigint not null default 1,
          unique(user_id, slug)
        )
        """,
        "create index if not exists idx_user_cards_user on user_character_cards(user_id, enabled, priority desc)",
        "create index if not exists idx_user_cards_name on user_character_cards(user_id, lower(name))",
    ]),
    (9, "import_jobs", [
        # 拆书流水线状态持久化，页面刷新可继续看进度，可取消
        """
        create table if not exists import_jobs (
          id bigint generated by default as identity primary key,
          job_id text unique not null,
          user_id bigint not null references users(id) on delete cascade,
          script_id bigint references scripts(id) on delete set null,
          status text not null default 'pending',
          stage text not null default 'pending',
          stage_progress integer not null default 0,
          stage_total integer not null default 0,
          overall_progress integer not null default 0,
          overall_total integer not null default 5,
          cancel_requested boolean not null default false,
          budget_estimate jsonb not null default '{}'::jsonb,
          usage_actual jsonb not null default '{}'::jsonb,
          stages jsonb not null default '[]'::jsonb,
          error text not null default '',
          started_at timestamptz,
          finished_at timestamptz,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now()
        )
        """,
        "create index if not exists idx_import_jobs_user on import_jobs(user_id, created_at desc)",
        "create index if not exists idx_import_jobs_script on import_jobs(script_id, created_at desc)",
    ]),
    (10, "pgvector_columns_and_hnsw", [
        # 仅当 vector 扩展已启用时建 vector 列 + HNSW；否则保持 jsonb fallback
        # 用 DO 块按运行时条件执行
        """
        do $$
        begin
          if exists (select 1 from pg_extension where extname = 'vector') then
            -- 加 vector 列（768 维，gemini embedding 标准；可后续调整）
            execute 'alter table document_chunks add column if not exists embedding_vec vector(768)';
            execute 'alter table memories add column if not exists embedding_vec vector(768)';
            -- HNSW 索引（cosine）
            execute 'create index if not exists idx_doc_chunks_embedding_hnsw on document_chunks using hnsw (embedding_vec vector_cosine_ops)';
            execute 'create index if not exists idx_memories_embedding_hnsw on memories using hnsw (embedding_vec vector_cosine_ops)';
          end if;
        end $$;
        """,
    ]),
    (11, "user_runtime_db_backed", [
        # B2: runtime 元数据 DB 化。原 platform_data/runtime/user_{id}.json 的内容搬到这里。
        # 状态快照（state_snapshot）继续放在 runtime_checkouts；这里只放 user→当前激活 save 的指针。
        """
        create table if not exists user_runtime (
          user_id bigint primary key references users(id) on delete cascade,
          save_id bigint references game_saves(id) on delete set null,
          active_commit_id bigint,
          active_branch_node_id bigint,
          active_ref_id bigint,
          source_state_path text not null default '',
          runtime_state_path text not null default '',
          game_url text not null default '/',
          metadata jsonb not null default '{}'::jsonb,
          updated_at timestamptz not null default now()
        )
        """,
        "create index if not exists idx_user_runtime_save on user_runtime(save_id)",
    ]),
    (12, "import_jobs_kind_for_durable_sync", [
        # B5: 让 import_jobs 同时承载 full_pipeline 和 knowledge_sync 两类任务
        "alter table import_jobs add column if not exists kind text not null default 'full_pipeline'",
        "create index if not exists idx_import_jobs_kind_user on import_jobs(kind, user_id, status, created_at desc)",
    ]),
    (13, "import_jobs_single_active_per_script", [
        # B5 加固：同 (user_id, script_id, kind) 在 pending/running 状态下只能有一行。
        # 配合 _schedule_knowledge_sync 的 INSERT ... ON CONFLICT DO NOTHING 做原子去重 +
        # _run_sync_job 的 UPDATE ... RETURNING 做原子领取，避免多进程重复跑同一任务。
        """
        create unique index if not exists uq_import_jobs_active_per_script
        on import_jobs(user_id, script_id, kind)
        where status in ('pending', 'running')
        """,
        # heartbeat 用于回收死掉的 worker 占用的任务（守护进程巡检超时 running 用）
        "alter table import_jobs add column if not exists heartbeat_at timestamptz",
        "create index if not exists idx_import_jobs_heartbeat on import_jobs(status, heartbeat_at) where status = 'running'",
    ]),
    (14, "script_timeline_anchors", [
        # 给"剧本时间线"建一个聚合锚点表。
        # 现状:每本剧本的 chapter_facts 已经有 story_phase + story_time_label,
        # 形成天然的"线性时间线"(初期穿越与火星线 / 柏林暗流篇 / 战争与成长线 / ...),
        # 但没有聚合表,/set 时间 / GM retrieval 都查不到对应章节范围。
        # 这个表把 chapter_facts group by (script_id, story_phase, story_time_label),
        # 拿到 (chapter_min, chapter_max, count, sample),
        # 供 resolve_timeline_anchor(script_id, label) 模糊匹配。
        """
        create table if not exists script_timeline_anchors (
          id bigint generated by default as identity primary key,
          script_id bigint not null references scripts(id) on delete cascade,
          story_phase text not null default '',
          story_time_label text not null default '',
          chapter_min integer not null,
          chapter_max integer not null,
          chapter_count integer not null default 0,
          sample_title text not null default '',
          sample_summary text not null default '',
          keywords text[] not null default '{}',
          confidence real not null default 1.0,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now(),
          unique (script_id, story_phase, story_time_label)
        )
        """,
        "create index if not exists ix_sta_script_phase on script_timeline_anchors(script_id, story_phase)",
        "create index if not exists ix_sta_script_label on script_timeline_anchors(script_id, story_time_label)",
        "create index if not exists ix_sta_script_chmin on script_timeline_anchors(script_id, chapter_min)",
    ]),
    (15, "worldline_convergence_anchors", [
        # task 136: 世界线收束机制 (Steins;Gate / 死神来了 风格)
        # 原著的关键事件 (chapter_facts.events + phase_digests.key_events) 是"锚点"。
        # 锚点必须发生,但发生的方式可以变。GM 每一回合知道接下来该发生哪几个锚点,
        # 主动设计场景把剧情往那里引。
        #
        # 本表只跟踪锚点的【发生状态】,不复制事件内容。
        # 事件文本按需从 chapter_facts / phase_digests 实时取。
        #
        # anchor_key 设计:
        #   "chapter:{chapter}:event:{event_idx}"   ← 来自 chapter_facts.events[idx]
        #   "phase:{phase_index}:event:{event_idx}" ← 来自 phase_digests.key_events[idx]
        # 这样不会因事件文本变化而失联。
        """
        create table if not exists save_anchor_states (
          id bigint generated by default as identity primary key,
          save_id bigint not null references game_saves(id) on delete cascade,
          anchor_key text not null,

          -- 数据来源 (溯源 + 反向查事件内容)
          source_kind text not null default 'chapter',  -- 'chapter' | 'phase'
          source_chapter integer,                         -- chapter_facts.chapter
          source_event_index integer not null default 0,  -- jsonb 数组里的下标
          source_phase_index integer,                     -- phase_digests.phase_index (script 级)
          script_id bigint not null references scripts(id) on delete cascade,

          -- 锚点元数据 (seed 时由 anchor_seed_agent 写入)
          summary text not null,            -- "穆蕾莉娅向 MC 透露异端情报"
          phase_label text not null default '',
          must_preserve jsonb not null default '[]'::jsonb,  -- ["信息传递", "异端话题"]
          may_vary jsonb not null default '[]'::jsonb,       -- ["地点", "时机", "旁观者"]
          importance integer not null default 50,   -- 0-100, 越大越关键
          is_fatal boolean not null default false,  -- true=死神来了模式,玩家任何阻止都失败

          -- 发生状态
          status text not null default 'pending',
            -- pending: 还没发生
            -- occurred: 按原著方式发生 (drift=0)
            -- variant: 以变体方式发生 (drift>0,核心保留)
            -- superseded: 被剧情绕过 (rare,需 reason)
          variant_description text not null default '',
          occurred_at_turn integer,
          drift_score numeric(3,2) not null default 0.0,  -- 0=完全一致 1=完全变体

          metadata jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now(),
          unique (save_id, anchor_key)
        )
        """,
        "create index if not exists idx_anchor_states_save on save_anchor_states(save_id, status)",
        "create index if not exists idx_anchor_states_phase on save_anchor_states(save_id, phase_label, status)",
        "create index if not exists idx_anchor_states_pending_importance on save_anchor_states(save_id, status, importance desc) where status = 'pending'",
        # script_id 反向索引,用于 seed 时按 script 拉全量锚点
        "create index if not exists idx_anchor_states_script on save_anchor_states(script_id, save_id)",
    ]),
    (16, "script_overrides", [
        # v16: 剧本 overrides 元数据 (signature tokens / suggestion rules /
        # phase inference / time_label_inference / known_names / known_locations 等)。
        # 从 modules/_script_overrides/<key>.json 迁移到 DB,为剧本分享 + 多用户隔离做准备。
        """
        create table if not exists script_overrides (
          script_id bigint primary key references scripts(id) on delete cascade,
          data jsonb not null default '{}'::jsonb,
          updated_at timestamptz not null default now()
        )
        """,
        "create index if not exists idx_script_overrides_updated on script_overrides(updated_at)",
    ]),
    (17, "ingestion_chapter_quality_columns", [
        # v17: Stage -1 摄入清洗 (Phase A.0)。给 script_chapters 加摄入质量列,
        # 让规则融合自适应切分 + 三道过滤的结果可落库并被提取/复核消费。
        #   is_author_note          — 作者非正文 (卷末通知/感言/请假等,抓 ~21.5% 污染)
        #   exclude_from_extraction — 不喂提取/不当剧情章 (默认 = is_author_note)
        #   title_confidence        — 标题可信度 0-1 (怪标题玩梗 → 低)
        #   content_descriptor      — 标题不可信时用的内容描述符 (下游提取/时间线用它,非原标题)
        "alter table script_chapters add column if not exists is_author_note boolean not null default false",
        "alter table script_chapters add column if not exists exclude_from_extraction boolean not null default false",
        "alter table script_chapters add column if not exists title_confidence real not null default 1.0",
        "alter table script_chapters add column if not exists content_descriptor text not null default ''",
        "create index if not exists idx_script_chapters_extractable on script_chapters(script_id) where exclude_from_extraction = false",
    ]),
    (18, "kb_relational_world_tree", [
        # v18: Phase B/C — 关系型 KB(规范层 per-script 只读)+ 行级 COW 世界树(per-save)。
        # 设计 docs/design/BC_kb_schema_worldtree.md。世界知识从 state blob 迁出进行级表,
        # kb_* 成唯一真相源;每行打 born_commit(=写入时 active commit),分支=沿 commit 谱系
        # recursive CTE 取 newest-per-logical_key;fork 零拷贝;删除用 retired_at_commit tombstone。
        # ---- Phase B 规范层(per-script,钉死只读,提取产出)----
        """
        create table if not exists kb_canon_entities (
          id bigint generated by default as identity primary key,
          script_id bigint not null references scripts(id) on delete cascade,
          logical_key text not null,
          name text not null,
          aliases jsonb not null default '[]'::jsonb,
          type text not null,
          summary text not null default '',
          attrs jsonb not null default '{}'::jsonb,
          first_revealed_chapter integer not null default 0,
          public_knowledge boolean not null default false,
          importance integer not null default 0,
          metadata jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now(),
          unique(script_id, logical_key)
        )
        """,
        "create index if not exists idx_kb_canon_entities_type on kb_canon_entities(script_id, type)",
        "create index if not exists idx_kb_canon_entities_reveal on kb_canon_entities(script_id, first_revealed_chapter)",
        """
        create table if not exists script_worldlines (
          id bigint generated by default as identity primary key,
          script_id bigint not null references scripts(id) on delete cascade,
          wl_key text not null,
          label text not null,
          parent_wl text,
          branch_at_node text,
          is_primary boolean not null default false,
          source text not null default 'extracted',
          metadata jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now(),
          unique(script_id, wl_key)
        )
        """,
        """
        create table if not exists script_worldline_nodes (
          id bigint generated by default as identity primary key,
          script_id bigint not null references scripts(id) on delete cascade,
          wl_key text not null,
          node_key text not null,
          seq integer not null,
          label text not null,
          summary text not null default '',
          chapter_min integer,
          chapter_max integer,
          anchor_keys jsonb not null default '[]'::jsonb,
          must_preserve jsonb not null default '[]'::jsonb,
          may_vary jsonb not null default '[]'::jsonb,
          causal_centrality real not null default 0,
          first_revealed_chapter integer not null default 0,
          created_at timestamptz not null default now(),
          unique(script_id, wl_key, node_key)
        )
        """,
        "create index if not exists idx_worldline_nodes_seq on script_worldline_nodes(script_id, wl_key, seq)",
        # ---- Phase C 活态层(per-save,行级 COW,挂现有 branch_commits)----
        """
        create table if not exists kb_entities (
          id bigint generated by default as identity primary key,
          save_id bigint not null references game_saves(id) on delete cascade,
          born_commit bigint not null references branch_commits(id) on delete cascade,
          logical_key text not null,
          name text not null,
          type text not null,
          status text not null default 'active',
          summary text not null default '',
          attrs jsonb not null default '{}'::jsonb,
          retired_at_commit bigint references branch_commits(id) on delete set null,
          origin text not null default 'player',
          metadata jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now()
        )
        """,
        "create index if not exists idx_kb_entities_key on kb_entities(save_id, logical_key, born_commit)",
        "create index if not exists idx_kb_entities_born on kb_entities(save_id, born_commit)",
        """
        create table if not exists kb_events (
          id bigint generated by default as identity primary key,
          save_id bigint not null references game_saves(id) on delete cascade,
          born_commit bigint not null references branch_commits(id) on delete cascade,
          logical_key text not null,
          story_time text not null default '',
          summary text not null default '',
          participants jsonb not null default '[]'::jsonb,
          location text not null default '',
          retired_at_commit bigint references branch_commits(id) on delete set null,
          metadata jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now()
        )
        """,
        "create index if not exists idx_kb_events_key on kb_events(save_id, logical_key, born_commit)",
        "create index if not exists idx_kb_events_born on kb_events(save_id, born_commit)",
        """
        create table if not exists kb_relationships (
          id bigint generated by default as identity primary key,
          save_id bigint not null references game_saves(id) on delete cascade,
          born_commit bigint not null references branch_commits(id) on delete cascade,
          logical_key text not null,
          from_key text not null default '',
          to_key text not null default '',
          kind text not null default '',
          note text not null default '',
          retired_at_commit bigint references branch_commits(id) on delete set null,
          metadata jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now()
        )
        """,
        "create index if not exists idx_kb_relationships_key on kb_relationships(save_id, logical_key, born_commit)",
        """
        create table if not exists kb_worldline_vars (
          id bigint generated by default as identity primary key,
          save_id bigint not null references game_saves(id) on delete cascade,
          born_commit bigint not null references branch_commits(id) on delete cascade,
          logical_key text not null,
          value jsonb,
          retired_at_commit bigint references branch_commits(id) on delete set null,
          created_at timestamptz not null default now()
        )
        """,
        "create index if not exists idx_kb_worldline_vars_key on kb_worldline_vars(save_id, logical_key, born_commit)",
        """
        create table if not exists kb_checkpoints (
          id bigint generated by default as identity primary key,
          save_id bigint not null references game_saves(id) on delete cascade,
          commit_id bigint not null references branch_commits(id) on delete cascade,
          snapshot jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now(),
          unique(save_id, commit_id)
        )
        """,
        # ---- 规范实体嵌入(BGE-M3 1024 维,仅 vector 扩展可用时;ivfflat 索引延到 Phase A 填充后建)----
        """
        do $$
        begin
          if exists (select 1 from pg_extension where extname = 'vector') then
            execute 'alter table kb_canon_entities add column if not exists embedding vector(1024)';
          end if;
        end $$;
        """,
    ]),
    (19, "kb_canon_embedding_dim_768", [
        # v19: 对齐现网嵌入。设计原写 BGE-M3(1024),但平台实际可用的是
        # Vertex text-embedding-004(768 维,knowledge.embedding 已封装)。
        # 自托管 BGE-M3 未部署 → 改用 768 复用现有嵌入栈(更省、已 live)。表为空,安全 alter。
        """
        do $$
        begin
          if exists (select 1 from pg_extension where extname = 'vector')
             and exists (select 1 from information_schema.columns
                         where table_name='kb_canon_entities' and column_name='embedding') then
            execute 'alter table kb_canon_entities drop column embedding';
            execute 'alter table kb_canon_entities add column embedding vector(768)';
          end if;
        end $$;
        """,
    ]),
    (20, "script_content_fingerprint_dedup", [
        # v20: Phase G 公开书共享去重。content_fingerprint = 归一正文 hash + 章数 + 字数;
        # 导入时命中已提取的 shareable 公开书 → 直接复用规范层(零提取成本)。
        "alter table scripts add column if not exists content_fingerprint text not null default ''",
        "alter table scripts add column if not exists shareable boolean not null default false",
        "create index if not exists idx_scripts_fingerprint on scripts(content_fingerprint) where content_fingerprint <> ''",
    ]),
    (21, "extraction_quota_and_spend", [
        # v21: Phase G 提取配额 + 成本记账。提取走 BYOK(用户付费),配额主要限平台编排
        # 负载 + 给用户成本透明;每用户每月一行,记本数 + 估算花费。
        """
        create table if not exists extraction_quota (
          id bigint generated by default as identity primary key,
          user_id bigint not null references users(id) on delete cascade,
          period text not null,                      -- 'YYYY-MM'
          books_extracted integer not null default 0,
          est_usd_spent numeric(10,4) not null default 0,
          updated_at timestamptz not null default now(),
          unique(user_id, period)
        )
        """,
        "create index if not exists idx_extraction_quota_user on extraction_quota(user_id, period)",
    ]),
    (22, "lazy_incremental_extraction_markers", [
        # v22: Phase G/W5 懒/增量提取。提取按玩家进度切片(过进度的反正被防剧透过滤,
        # 急切全书提取浪费)。extracted_through_chapter=已提取到的最大章;extraction_seeded=
        # Pass0 种子/纪元是否已做(只做一次)。
        "alter table scripts add column if not exists extracted_through_chapter integer not null default 0",
        "alter table scripts add column if not exists extraction_seeded boolean not null default false",
    ]),
    (23, "sessions_token_hash_security", [
        # v23: 会话令牌哈希化(安全)。不在 DB 存明文 session token,存 sha256(token);
        # 按 hash 查找/删除。修复部分环境 token_hash NOT NULL 但 login 未填的漂移,
        # 并统一到"哈希存储"(拖库不直接拿到可用 session token)。
        "alter table sessions add column if not exists token_hash text",
        # 容错:历史/漂移环境可能 NOT NULL 且无默认 → 放开,改由代码填哈希
        "alter table sessions alter column token_hash drop not null",
        "alter table sessions alter column token drop not null",
        # 回填存量明文 session 的哈希(SHA-256 hex)
        "update sessions set token_hash = encode(digest(token, 'sha256'), 'hex') "
        "where token_hash is null and coalesce(token,'') <> '' and exists "
        "(select 1 from pg_extension where extname='pgcrypto')",
        "create index if not exists idx_sessions_token_hash2 on sessions(token_hash)",
    ]),
    (24, "save_last_played_at", [
        # v24: 存档「最后游玩日期」。autosave 是每个存档每回合无感提交,不再有独立
        # 「当前自动存档」槽;列表显示最后游玩时间。回填存量为 updated_at。
        "alter table game_saves add column if not exists last_played_at timestamptz",
        "update game_saves set last_played_at = updated_at where last_played_at is null",
        "create index if not exists idx_game_saves_last_played on game_saves(user_id, last_played_at desc)",
    ]),
]


def _assert_migrations_monotonic() -> None:
    """启动时自检：MIGRATIONS 列表必须按 version 升序且无重复。
    否则 _apply_versioned_migrations 会按列表顺序乱跑，产生难调试的 bug。
    """
    seen: set[int] = set()
    last = 0
    for version, name, _ in MIGRATIONS:
        if version in seen:
            raise RuntimeError(f"migration v{version} 重复（{name}）")
        if version <= last:
            raise RuntimeError(
                f"migration v{version}（{name}）顺序错乱：必须严格递增，前一个是 v{last}"
            )
        seen.add(version)
        last = version


# 模块加载时立即自检，部署前就能发现列表写错
_assert_migrations_monotonic()


@contextmanager
def _migration_advisory_lock():
    """Postgres advisory lock 串行化 DDL 阶段。

    - 用独立短连接避免污染 pool
    - 设置 lock_timeout，等不到锁直接 raise 而不是无限等
    - 出现异常也会释放（连接关闭自动释放）
    """
    conn = psycopg.connect(database_url())
    try:
        with conn.cursor() as cur:
            cur.execute(f"set lock_timeout = {MIGRATION_LOCK_TIMEOUT_MS}")
            cur.execute("select pg_advisory_lock(%s)", (MIGRATION_ADVISORY_LOCK_ID,))
        conn.commit()
        try:
            yield conn
        finally:
            try:
                with conn.cursor() as cur:
                    cur.execute("select pg_advisory_unlock(%s)", (MIGRATION_ADVISORY_LOCK_ID,))
                conn.commit()
            except Exception:
                pass
    finally:
        conn.close()


def _assert_schema_up_to_date() -> None:
    """生产模式下的 fail-fast 检查：DB 已应用版本必须 >= 代码登记的最高版本。"""
    expected_versions = {v for v, _, _ in MIGRATIONS}
    if not expected_versions:
        return
    try:
        with _get_connect()() as db:
            row = db.execute(
                "select to_regclass('schema_migrations') as exists_"
            ).fetchone()
            if not row or not row.get("exists_"):
                raise RuntimeError(
                    "schema_migrations 表不存在；请先运行 `python -m platform_app.migrate up`"
                )
            applied = {int(r["version"]) for r in db.execute(
                "select version from schema_migrations"
            ).fetchall()}
    except psycopg.OperationalError as exc:
        raise RuntimeError(f"无法连接数据库做版本检查: {exc}") from exc
    missing = sorted(expected_versions - applied)
    if missing:
        raise RuntimeError(
            f"schema 落后于代码：缺少 migration {missing}。"
            f"请运行 `python -m platform_app.migrate up` 后再启动服务。"
        )


def _apply_versioned_migrations() -> None:
    _migrations = _get_migrations()
    with _get_connect()() as db:
        db.execute(
            """
            create table if not exists schema_migrations (
              version integer primary key,
              name text not null,
              applied_at timestamptz not null default now()
            )
            """
        )
        applied = {int(r["version"]) for r in db.execute("select version from schema_migrations").fetchall()}
        for version, name, statements in _migrations:
            if version in applied:
                continue
            for stmt in statements:
                db.execute(stmt)
            db.execute(
                "insert into schema_migrations(version, name) values (%s, %s) on conflict do nothing",
                (version, name),
            )


def list_migrations() -> dict[str, Any]:
    """诊断接口：列出所有已知 migration 和应用状态。

    fresh DB（schema_migrations 表都还没建）也必须返回 ok，标记所有项 applied=False。
    `python -m platform_app.migrate status` 是部署前第一道诊断，不能因为表没建就炸。
    """
    try:
        with _get_connect()() as db:
            row = db.execute(
                "select to_regclass('schema_migrations') as exists_"
            ).fetchone()
            schema_table_exists = bool(row and row.get("exists_"))
            if schema_table_exists:
                applied = {int(r["version"]): r for r in db.execute(
                    "select version, name, applied_at from schema_migrations"
                ).fetchall()}
            else:
                applied = {}
        _migrations = _get_migrations()
        items = []
        for version, name, _ in _migrations:
            row = applied.get(version)
            items.append({
                "version": version,
                "name": name,
                "applied": row is not None,
                "applied_at": str(row["applied_at"]) if row else None,
            })
        return {
            "ok": True,
            "migrations": items,
            "total_known": len(_migrations),
            "total_applied": len(applied),
            "schema_table_exists": schema_table_exists,
            "fresh_database": not schema_table_exists,
        }
    except Exception as exc:
        return {"ok": False, "error": str(exc)}
